### PR TITLE
Forward port of client mode delete from 1.4

### PR DESCRIPTION
**Pull request by jonmeredith**
Manually applied patch generated from diff of PR@1022 on 1.4 branch.
The branch invovled a number of other modules that weren't needed
and made the merge too hard.

Original PR #1022 merged against 1.4 (for 1.4.11 release)
in commit 1fbb8156068e203cfe3997c79fa50bef1a03b9ee

### CODE REVIEW

**Comment by jonmeredith** [comment]
@krestenkrab please could you verify I forward ported correctly.  `do_delete` changed signature slightly.

**Comment by jonmeredith** [comment]
basho/riak_test#687 adds the r_t to master.

**Comment by krestenkrab** [comment]
+1. Looks good.

**Comment by jonmeredith** [comment]
@borshop: retry

unrelated looking eunit failure

**Comment by engelsanchez** [comment]
The test is failing because the KV_DELETE_REQ macro now points to a version 2 delete request. The code in fsm_eqc_vnode:active needs to change to match properly.

**Comment by yorkshire-steve** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
