### PR TITLE
Update repair count type specs in riak_kv_entropy_info

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Change the repaired field of the exchange_info record in the 
riak_kv_entropy_info module from a type of pos_integer() to non_neg_integer().
Also change the Repaired parameter type for 
riak_kv_entropy_info:exchange_complete/4 and 
riak_kv_entropy_info:exchange_complete/5 to be non_neg_integer().

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
This should resolve [this](https://github.com/basho/yokozuna/issues/384) dialyzer problem with yokozuna that is preventing PRs from merging.

**Comment by reiddraper** [comment]
This change is to allow `0` to be a valid value?

**Comment by kellymclaughlin** [comment]
Correct

**Comment by reiddraper** [comment]
@borshop merge

**Pull request merged**
