### PR TITLE
Add "never" atom to options for anti_entropy_expire config.

### PR DESCRIPTION
**Pull request by seancribbs**
This should address #809.

### CODE REVIEW

**Comment by seancribbs** [comment]
This will also need:
- [x] CSE approval
- [x] PM approval

**Comment by seancribbs** [comment]
@gburd @angrycub @jmshoffs0812

**Comment by angrycub** [comment]
+1

**Comment by gburd** [comment]
+1

**Comment by seancribbs** [comment]
. @kuenishi already confirmed this works. Merging.

**Pull request merged**
