### PR TITLE
Setting "object.format" should not be in the default config file. [JIRA: RIAK-3372]

### PR DESCRIPTION
**Pull request by seancribbs**
This setting is only for use in upgrades/downgrades from versions 1.3 and earlier.
- [x] CSE approval
- [x] PM approval

### CODE REVIEW

**Comment by seancribbs** [comment]
@gburd @angrycub

**Comment by seancribbs** [comment]
This should be delayed until 2.1. Users upgrading from 1.3 might not be able to downgrade easily without this setting being more explicitly set to '0', if the upgrade to 2.0 does not go well.

**Comment by angrycub** [comment]
Agreed, @seancribbs.  I agree with the PR, just not the timing.

**Comment by gburd** [comment]
seems ok to me, +1

**Comment by seancribbs** [comment]
Milestone is set on this then, we'll revisit after 2.0 release.

**Comment by angrycub** [comment]
Create jira issue

**Comment by yorkshire-steve** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
