### PR TITLE
Check send_output return when sending 2I results to a pipe.

### PR DESCRIPTION
**Pull request by jonmeredith**
Propagate error returns from riak_pipe_vnode_worker:send_output.  Pipes will now error rather than returning a result without all entries processed.

Depends on basho/riak_pipe#42 being merged.

Tested with idxh module in systest.

Configure pipe with low worker count

```
[{riak_pipe, [{worker_limit, 2},
              {worker_queue_limit, 1}]},
```

Set up fixtures

```
idxh:fixtures().
```

```
(dev1@127.0.0.1)1> [spawn(fun() -> idxh:searchpbc() end) || I <- lists:seq(1,3)].
[<0.417.0>,<0.418.0>,<0.419.0>]
(dev1@127.0.0.1)2> 09:15:06.859 [error] gen_fsm <0.447.0> in state waiting_results terminated with reason: {error,worker_limit_reached}
09:15:06.859 [error] Error sending inputs: {error,worker_limit_reached}
Search <<"b">> / <<"idx1_bin">> = <<"x">>
 {error,<<"Error sending inputs: {error,worker_limit_reached}">>}
(dev1@127.0.0.1)2> 09:15:06.862 [error] CRASH REPORT Process <0.447.0> with 2 neighbours crashed with reason: {error,worker_limit_reached}
09:15:06.863 [error] Supervisor riak_pipe_qcover_sup had child undefined started with {riak_core_coverage_fsm,start_link,undefined} at <0.447.0> exit with reason {error,worker_limit_reached} in context child_terminated
09:15:06.865 [error] Supervisor riak_pipe_builder_sup had child undefined started with {riak_pipe_builder,start_link,undefined} at <0.435.0> exit with reason {error,worker_limit_reached} in context child_terminated
Search <<"b">> / <<"idx1_bin">> = <<"x">>
 {ok,[[<<"b">>,<<"k1">>],
      [<<"b">>,<<"k2">>],
      [<<"b">>,<<"k3">>],
      [<<"b">>,<<"k4">>],
      [<<"b">>,<<"k5">>],
      [<<"b">>,<<"k6">>]]}
Search <<"b">> / <<"idx1_bin">> = <<"x">>
 {ok,[[<<"b">>,<<"k1">>],
      [<<"b">>,<<"k2">>],
      [<<"b">>,<<"k4">>],
      [<<"b">>,<<"k5">>],
      [<<"b">>,<<"k6">>],
      [<<"b">>,<<"k3">>]]}
(dev1@127.0.0.1)2> 
```

### CODE REVIEW

**Comment by rzezeski** [comment]
I'm still seeing incorrect results for 2I/MR over HTTP.

Steps to reproduce:
- use my branch of bench: https://github.com/basho/basho_bench/tree/rz-hack-2i-driver
- `(cd deps/riak_kv && git checkout jdm-pipe-2i-check-send-output-1.1)`
- `make && make stagedevrel`
- Set `worker_limit` and `worker_queue_limit` as Jon says above
- Use the following config to populate data:
  
  ```
  {driver,
      basho_bench_driver_2i}.
  
  {operations, [
      %% {get_pb, 1},
      {{put_pb, 5}, 20}
      %% {{query_http, 10}, 1},
      %% {{query_mr,   100}, 1}
      %% {{query_pb,   10}, 1}
  ]}.
  
  {mode, max}.
  {duration, 2}.
  {concurrent, 2}.
  
  {key_generator, {sequential_int, 1000}}.
  {value_generator, {fixed_bin, 1000}}.
  {max_key, 1000}.
  
  {pb_ips, ["127.0.0.1"]}.
  {pb_port, 8081}.
  {pb_replies, 1}.
  
  {http_hosts, ["127.0.0.1"]}.
  {http_port, 8091}.
  
  {rng_seed, {1, 2, 3}}.
  
  {code_paths, ["/Users/rzezeski/work/riak_kv/deps/mochiweb"]}.
  ```
- Use the following config to query the data:
  
  ```
  {driver,
      basho_bench_driver_2i}.
  
  {operations, [
      {{query_mr,   100}, 1}
  ]}.
  
  {mode, max}.
  {duration, 2}.
  {concurrent, 2}.
  
  {key_generator, {uniform_int, 1000}}.
  {value_generator, {fixed_bin, 1000}}.
  {max_key, 1000}.
  
  {pb_ips, ["127.0.0.1"]}.
  {pb_port, 8081}.
  {pb_replies, 1}.
  
  {http_hosts, ["127.0.0.1"]}.
  {http_port, 8091}.
  
  {rng_seed, {1, 2, 3}}.
  
  {code_paths, ["/Users/rzezeski/work/riak_kv/deps/mochiweb"]}.
  ```
- Notice lines like the following in the bench output:
  
  ```
  Not enough results for query_mr: 113/212/[[<<"mybucket">>,<<"130">>],
                                            [<<"mybucket">>,<<"137">>],
                                            [<<"mybucket">>,<<"140">>],
                                            [<<"mybucket">>,<<"145">>],
                                            [<<"mybucket">>,<<"115">>],
                                            [<<"mybucket">>,<<"161">>],
                                            [<<"mybucket">>,<<"144">>],
                                            [<<"mybucket">>,<<"122">>],
                                            [<<"mybucket">>,<<"204">>],
                                            [<<"mybucket">>,<<"162">>],
                                            [<<"mybucket">>,<<"150">>],
                                            [<<"mybucket">>,<<"210">>],
                                            [<<"mybucket">>,<<"177">>],
                                            [<<"mybucket">>,<<"193">>],
                                            [<<"mybucket">>,<<"195">>],
                                            [<<"mybucket">>,<<"212">>],
                                            [<<"mybucket">>,<<"197">>]]
  Not enough results for query_mr: 636/735/[]
  Not enough results for query_mr: 313/412/[[<<"mybucket">>,<<"318">>],
  ```

**Comment by jonmeredith** [comment]
Needs to be used in conjunction with basho/riak_pipe#43

**Comment by rzezeski** [comment]
Cannot reproduce incorrect results.  +1 to merge

**Comment by rzezeski** [comment]
+1 again after the repull...can't produce incorrect results.

**Comment by Jasson** [comment]
I met it too.  thanks ,it resolved

**Pull request merged**
