### PR TITLE
qry_buffers: generate small file names for temp tables

### PR DESCRIPTION
**Pull request by hmmr**
Cherry-pick d00471f5586 (#1626, which went into 1.5.2) to generate small file names for qbuf temp tables.

### CODE REVIEW

**Comment by hazen** [comment]
Looks good, but I'll give it a proper test in the morning.  Sorry.

**Comment by hazen** [comment]
```
Test Results:
ts_simple_aggregation_math-riak_kv_eleveldb_backend,riak_kv_multi_backend                            : pass
ts_simple_api-riak_kv_eleveldb_backend,riak_kv_multi_backend                                         : pass
ts_simple_batch-riak_kv_eleveldb_backend,riak_kv_multi_backend                                       : pass
ts_simple_blob-riak_kv_eleveldb_backend,riak_kv_multi_backend                                        : pass
ts_simple_create_table_already_created-riak_kv_eleveldb_backend,riak_kv_multi_backend                : pass
ts_simple_create_table_dup_primary_key-riak_kv_eleveldb_backend,riak_kv_multi_backend                : pass
ts_simple_create_table_no_primary_key-riak_kv_eleveldb_backend,riak_kv_multi_backend                 : pass
ts_simple_create_table_not_null_pk_fields-riak_kv_eleveldb_backend,riak_kv_multi_backend             : pass
ts_simple_create_table_pass_1-riak_kv_eleveldb_backend,riak_kv_multi_backend                         : pass
ts_simple_create_table_split_key-riak_kv_eleveldb_backend,riak_kv_multi_backend                      : pass
ts_simple_describe_table-riak_kv_eleveldb_backend,riak_kv_multi_backend                              : pass
ts_simple_div_by_zero-riak_kv_eleveldb_backend,riak_kv_multi_backend                                 : pass
ts_simple_explain_query-riak_kv_eleveldb_backend,riak_kv_multi_backend                               : pass
ts_simple_get-riak_kv_eleveldb_backend,riak_kv_multi_backend                                         : pass
ts_simple_get_not_found-riak_kv_eleveldb_backend,riak_kv_multi_backend                               : pass
ts_simple_http_api_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                              : fail
ts_simple_http_security_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                         : pass
ts_simple_insert-riak_kv_eleveldb_backend,riak_kv_multi_backend                                      : pass
ts_simple_insert_incorrect_columns-riak_kv_eleveldb_backend,riak_kv_multi_backend                    : pass
ts_simple_insert_iso8601-riak_kv_eleveldb_backend,riak_kv_multi_backend                              : pass
ts_simple_invdist_funs_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                          : fail
ts_simple_latin1_create_table_not_allowed-riak_kv_eleveldb_backend,riak_kv_multi_backend             : pass
ts_simple_object_size_limits-riak_kv_eleveldb_backend,riak_kv_multi_backend                          : pass
ts_simple_pb_security_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                           : pass
ts_simple_put-riak_kv_eleveldb_backend,riak_kv_multi_backend                                         : pass
ts_simple_put_all_datatypes-riak_kv_eleveldb_backend,riak_kv_multi_backend                           : pass
ts_simple_put_all_null_datatypes-riak_kv_eleveldb_backend,riak_kv_multi_backend                      : pass
ts_simple_put_bad_date-riak_kv_eleveldb_backend,riak_kv_multi_backend                                : pass
ts_simple_put_invalid_data-riak_kv_eleveldb_backend,riak_kv_multi_backend                            : pass
ts_simple_put_non_existent_bucket-riak_kv_eleveldb_backend,riak_kv_multi_backend                     : pass
ts_simple_query_buffers_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                         : pass
ts_simple_recompile_ddl-riak_kv_eleveldb_backend,riak_kv_multi_backend                               : pass
ts_simple_select-riak_kv_eleveldb_backend,riak_kv_multi_backend                                      : pass
ts_simple_select_compare_two_fields_not_allowed-riak_kv_eleveldb_backend,riak_kv_multi_backend       : pass
ts_simple_select_double_in_key-riak_kv_eleveldb_backend,riak_kv_multi_backend                        : pass
ts_simple_select_incompatible_type_float_not_allowed-riak_kv_eleveldb_backend,riak_kv_multi_backend  : pass
ts_simple_select_incompatible_type_integer_not_allowed-riak_kv_eleveldb_backend,riak_kv_multi_backend: pass
ts_simple_select_is_null-riak_kv_eleveldb_backend,riak_kv_multi_backend                              : pass
ts_simple_select_iso8601-riak_kv_eleveldb_backend,riak_kv_multi_backend                              : pass
ts_simple_select_missing_field_in_pk_not_allowed-riak_kv_eleveldb_backend,riak_kv_multi_backend      : pass
ts_simple_select_nogap-riak_kv_eleveldb_backend,riak_kv_multi_backend                                : pass
ts_simple_select_not_found-riak_kv_eleveldb_backend,riak_kv_multi_backend                            : pass
ts_simple_select_table_not_existing-riak_kv_eleveldb_backend,riak_kv_multi_backend                   : pass
ts_simple_select_unexpected_token_not_allowed-riak_kv_eleveldb_backend,riak_kv_multi_backend         : pass
ts_simple_select_where_has_no_lower_bounds_not_allowed-riak_kv_eleveldb_backend,riak_kv_multi_backend: pass
ts_simple_select_where_has_no_upper_bounds_not_allowed-riak_kv_eleveldb_backend,riak_kv_multi_backend: pass
ts_simple_show_create_table-riak_kv_eleveldb_backend,riak_kv_multi_backend                           : pass
ts_simple_show_tables-riak_kv_eleveldb_backend,riak_kv_multi_backend                                 : pass
ts_simple_single_key_ops-riak_kv_eleveldb_backend,riak_kv_multi_backend                              : pass
ts_simple_unicode_create_table_not_allowed-riak_kv_eleveldb_backend,riak_kv_multi_backend            : pass
ts_cluster_activate_table_pass_1-riak_kv_eleveldb_backend,riak_kv_multi_backend                      : pass
ts_cluster_aggregation-riak_kv_eleveldb_backend,riak_kv_multi_backend                                : pass
ts_cluster_capabilities_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                         : pass
ts_cluster_comprehensive-riak_kv_eleveldb_backend,riak_kv_multi_backend                              : fail
ts_cluster_coverage-riak_kv_eleveldb_backend,riak_kv_multi_backend                                   : pass
ts_cluster_create_table_pass_1-riak_kv_eleveldb_backend,riak_kv_multi_backend                        : pass
ts_cluster_create_table_via_sql_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                 : pass
ts_cluster_group_by_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                             : pass
ts_cluster_handoff_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                              : pass
ts_cluster_keys_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                                 : pass
ts_cluster_list_irreg_keys_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                      : pass
ts_cluster_overload_reported-riak_kv_eleveldb_backend,riak_kv_multi_backend                          : pass
ts_cluster_put_pass_1-riak_kv_eleveldb_backend,riak_kv_multi_backend                                 : pass
ts_cluster_quantum_boundaries_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                   : pass
ts_cluster_replication-riak_kv_eleveldb_backend,riak_kv_multi_backend                                : pass
ts_cluster_riak_shell_basic_sql-riak_kv_eleveldb_backend,riak_kv_multi_backend                       : pass
ts_cluster_riak_shell_regression_log-riak_kv_eleveldb_backend,riak_kv_multi_backend                  : pass
ts_cluster_select_desc_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                          : pass
ts_cluster_select_pass_1-riak_kv_eleveldb_backend,riak_kv_multi_backend                              : pass
ts_cluster_select_pass_2-riak_kv_eleveldb_backend,riak_kv_multi_backend                              : pass
ts_cluster_select_pass_3_sorted_on_key-riak_kv_eleveldb_backend,riak_kv_multi_backend                : pass
ts_cluster_stream_list_keys_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                     : pass
ts_cluster_table_active_state-riak_kv_eleveldb_backend,riak_kv_multi_backend                         : pass
ts_cluster_unicode-riak_kv_eleveldb_backend,riak_kv_multi_backend                                    : fail
ts_cluster_updowngrade_group_by_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                 : fail
ts_cluster_updowngrade_order_by_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend                 : fail
ts_cluster_updowngrade_select_aggregation_SUITE-riak_kv_eleveldb_backend,riak_kv_multi_backend       : fail
ts_cluster_w1c_delete-riak_kv_eleveldb_backend,riak_kv_multi_backend                                 : pass
ts_simple_activate_table_pass_1-riak_kv_eleveldb_backend,riak_kv_multi_backend                       : pass
ts_simple_activate_table_pass_2-riak_kv_eleveldb_backend,riak_kv_multi_backend                       : pass
ts_simple_aggregation-riak_kv_eleveldb_backend,riak_kv_multi_backend                                 : pass
ts_simple_aggregation_fail-riak_kv_eleveldb_backend,riak_kv_multi_backend                            : pass
---------------------------------------------
7 Tests Failed
75 Tests Passed
That's 91.46341463414635% for those keeping score
```

**Comment by hazen** [comment]
:+1:

**Comment by macintux** [comment]
+1

**Pull request merged**
