### PR TITLE
Spawn a monitoring process per get/ put fsm

### PR DESCRIPTION
**Pull request by russelldb**
Un-gen_serverize get_put_monitor
Move the get/put stats to riak stat
Remove unused all_stats/0 fun from get/put monitor
Update eqc test to work with a spawn per fsm

### CODE REVIEW

**Comment by lordnull** [comment]
The get and put fsm eqc tests fail; seems they don't tell the monitor.

Failing tests: 
    get_fsm_qc:49: eqc_test_...Failed! After 1 tests.
    put_fsm_eqc:84: eqc_test_...Failed! After 1 tests.

Key line on both:  told_monitor: failed

**Comment by joedevivo** [comment]
```
Test Results:
verify_riak_stats-bitcask: pass
```

Looks good saw far, will continue reading code

**Comment by joedevivo** [comment]
+1, I like it and can't wait for Peter Jackson's major motion picture adaptation.

**Comment by russelldb** [comment]
@lordnull interesting, I'll give that another look. I only updated the get_put_monitor_eqc test, didn't realise the others needed work. Ooops.

**Comment by joedevivo** [comment]
Yeah, I saw the same output as @lordnull. I'm embarrassed to say that I looked at the wrong terminal window for test output.

**Comment by russelldb** [comment]
@lordnull heh, so the test is tied strongly to the implementation of get_put monitor, now it is not a gen_server, that validation is meaningless. I'll see what I can do.

**Comment by russelldb** [comment]
Pushed updated eqc test and util. Passes on my machine…will it work on yours?

**Comment by joedevivo** [comment]
eqc pass on my machine, +1

**Comment by lordnull** [comment]
All tests pass, I'm sated :+1:

**Comment by russelldb** [comment]
Wooh. Thanks @lordnull!

**Pull request merged**
