### PR TITLE
Using riak_pipe for Map Reduce task may return inconsistent results when one of cluster node is down. 

### PR DESCRIPTION
**Pull request by dreyk**
Using riak_pipe for Map Reduce task may return inconsistent results(for example empty list,however all data are available).
1. We must generate constant hash for the output reduce pase taking account of which nodes are up.
2. We must return an error If can't send result of reduce(prereduce phase to the output)  because some node are failed during map reduce job and we can't send result to it.

See http://lists.basho.com/pipermail/riak-users_lists.basho.com/2013-January/010870.html

### CODE REVIEW

**Comment by beerriot** [comment]
As the github history indicates, I cleaned up the first patch in this PR (for the constant reduce hash) for incorporation into Riak's 1.3 RC2. We'll review the second patch (for handling reduce phase errors) separately.

Thank you!

**Comment by evanmcc** [comment]
@beerriot Did the second patch ever get merged?

**Comment by beerriot** [comment]
@evanmcc Nope, it sure didn't. Want to submit a PR?

**Comment by slfritchie** [comment]
Pulling PRs out of the freezer ... Hrm, looks like an impasse.  Does the 2nd patch exist someplace?

**Comment by evanmcc** [comment]
I don't think so.  It'd be a process of looking at this PR, and Bryan's
part 1 PR and diffing them and cleaning up/updating.

**Comment by yorkshire-steve** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
