### PR TITLE
Make w1c conflict resolution predictable

### PR DESCRIPTION
**Pull request by macintux**
By design, the write-once code path has deterministic but unpredictable sibling resolution. The objects are hashed and compared.

This was intended to discourage write-once updates.

Instead, choose the "last" write as determined by comparing timestamps on the version vectors. This can still fail to produce the desired results if the clocks on servers are out of sync, but will usually give the right answer.

### CODE REVIEW

**Comment by russelldb** [comment]
Genuinely sad to see that the designs I presented at the meet-up (and the explanation of how "just using the timestamp" approach is incorrect) have been ignored in favour of this. Why aren't we doing it properly when there are simple, correct existing designs?

**Comment by russelldb** [comment]
It does _not_ need out of sync clocks for dataloss to occur

**Comment by macintux** [comment]
Several discussions out of band have occurred on this, but I'm definitely not willing to merge this until we discuss whether this can go into KV, and if not, how we'd manage that conflict.

**Comment by macintux** [comment]
I just ripped this off in a hurry. I'm sorry, I had forgotten you had a better option. 

I'll be happy to take a better approach.

**Comment by macintux** [comment]
This is ready for review.

**Comment by hazen** [comment]
@russelldb Are you willing to live with @macintux's solution for the time being?  How to you propose we proceed?

**Comment by paegun** [comment]
+1 6dc807e

**Comment by macintux** [comment]
Pushed a new merge

**Comment by paegun** [comment]
+1 b34ab0f

**Comment by macintux** [comment]
@borshop merge

**Comment by nickelization** [comment]
@javajolt for those of us following along, did you ever get to follow up with @russelldb after your last comment? I'm just curious whether there was some discussion that happened out-of-band, or if we just went ahead and merged.

**Comment by macintux** [comment]
I’m the out of band. I talked with Russell, got a go-ahead, conveyed that to Brett.

**Comment by nickelization** [comment]
:thumbsup: cool, just wanted to make sure we didn't lose anything in the shuffle :)

**Pull request merged**
