### PR TITLE
Do not crash riak node if vnode status file is unreadable.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
If for any reason the vnode status file is unreadable with
file:consult/1 the vnode would start, fail to consult, crash until the
restart limit was hit and the node would fail to start/crash.

### CODE REVIEW

**Comment by jonmeredith** [comment]
+1 d32be75

**Comment by jsvisa** [comment]
Thanks  @mrallen1, but I want to know why the vnode status file becomes unreadable?

**Comment by jadeallenx** [comment]
It interprets the vnode status file as improper Unicode since that's the default file encoding in 17+

**Comment by russelldb** [comment]
Note, there is another PR needed for erlang 17+ that attempts to consult a pre 17 file as pre 17 encoding. @tburghart worked on it, but it's not needed until we support 17.

**Pull request closed without merging**
