### PR TITLE
try code:load_file if loading with code:ensure_loaded fails

### PR DESCRIPTION
**Pull request by hmmr**
`code:ensure_loaded` fails if our code server is in embedded mode, causing riak_cs to fail to configure riak with a custom backend storage:

``` {riak_kv,
     [{add_paths,
          ["/home/hmmr/X/titokyo/g/riak_cs/dev/dev1/riak-cs/lib/riak_cs-3.0.0pre3+build.3435.ref2aaece2f/ebin"]},
      {storage_backend,riak_cs_kv_multi_backend},
      ...
```

Loading the module with `code:load_file/1` actually makes it happen.

### CODE REVIEW

**Review by martinsumner — APPROVED** [review]

**Comment by martinsumner** [comment]
Another Riak user raised the issue of code in additional paths not working in riak_kv >= 3.0 (e.g. map/reduce functions), and returning {error, embedded} instead.

As part of the switch to OTP 20 with 3.0, the switch was made to relx - and this changes the default mode from interactive to embedded:

https://github.com/erlware/relx/blob/master/priv/templates/extended_bin#L923-L924

So it appears the root cause here is we're now running embedded.  But this wasn't a deliberate change.  So perhaps the best answer, to solve this and other dynamic code loading issues, is to switch back to interactive.

For packaged deployments - I think we could do this by setting the CODE_LOADING_MODE in the riak script https://github.com/basho/riak/blob/develop-3.0/rel/files/riak.  This wouldn't work though when running direct from `make rel` and `make devrel`.

Are there any objections to switching back to interactive mode? @martincox

**Comment by martinsumner** [comment]
See https://github.com/basho/riak/pull/1077

This changes the default back to interactive by using a pre_start script (as with changing the max log size).  This seems better than changing rel/fiiles/riak.

**Comment by hmmr** [comment]
As far as #1077 fixes the loading regression, I'm totally fine with the proposed change to interactive mode.

**Comment by hmmr** [comment]
Closing as basho/riak#1077 has been merged.

**Pull request closed without merging**
