### PR TITLE
Consuming the vnode_status output in stats was brittle

### PR DESCRIPTION
**Pull request by russelldb**
Fix to expect a list of more than one element

Or there is this way. With this test https://github.com/basho/riak_test/pull/690

Note that this way means extra output on `riak-admin vnode_status` as the vnodeid will be present.

See https://github.com/basho/riak_kv/pull/1034 for the other choice (and it's test)

### CODE REVIEW

**Comment by jonmeredith** [comment]
+1

Go with vnode status, that's what it is for.  Doesn't break anything else I could find with this patch, output is ok in `riak-admin vnode-status` and `verify_secondary_index_reformat.erl` and `riak_admin_console_tests.erl` look sane.

**Comment by jonmeredith** [comment]
+1 323a6817ea7e041c4f2c33575e60fc85fa1ce9b7

**Comment by russelldb** [comment]
@borshop: retry

**Comment by jonmeredith** [comment]
@borshop retry

Silly builders, works on my machine.

```
➜  riak_kv git:(bug/rdb/vnode-status) git branch
  2.0
* bug/rdb/vnode-status
… run tests ...
Finished in 115.552 seconds
287 tests, 0 failures
Cover analysis: /private/tmp/riak_kv/.eunit/index.html
```

**Comment by jonmeredith** [comment]
… and running it on the builder is ok too

```
[buildbot@build-centos-6-64 .eunit]$ /usr/local/erlang-r16b02/bin/erl erl -pa ../deps/*/ebin ../ebin .
Erlang R16B02-basho5 (erts-5.10.3) [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]

Eshell V5.10.3  (abort with ^G)
1> put_fsm_eqc:setup().
started
(putfsmeqc925010511055@build-centos-6-64)2> eqc:recheck(put_fsm_eqc:prop_basic_put()).
Starting Quviq QuickCheck version 1.31.3
   (compiled at {{2014,8,25},{12,13,51}})
Licence for Basho reserved until {{2014,10,16},{22,50,17}}
OK, test passed this time.
true
```

**Comment by russelldb** [comment]
@borshop: retry

**Comment by russelldb** [comment]
+1 8e485a8eb1e8b2a8472f09397abe085e1f1b796d

**Comment by russelldb** [comment]
@borshop merge

**Pull request merged**
