### PR TITLE
Don't encode object dot for JS map-reduce

### LINKED ISSUE #779: [DOWNGRADE?] The new dvv stuff doesn't play well with JS map-reduce
While running Yokozuna's map-reduce test I saw the following error.

```
[{xmerl_ucs,from_utf8,1,[{file,\"xmerl_ucs.erl\"},{line,185}]},
                         {mochijson2,json_encode_string,2,[{file,\"src/mochijson2.erl\"},{line,186}]},
                         {mochijson2,'-json_encode_proplist/2-fun-0-',3,[{file,\"src/mochijson2.erl\"},{line,167}]},
                         {lists,foldl,3,[{file,\"lists.erl\"},{line,1248}]},
                         {mochijson2,json_encode_proplist,2,[{file,\"src/mochijson2.erl\"},{line,170}]},
                         {riak_kv_wm_mapred,send_error,2,[{file,\"src/riak_kv_wm_mapred.erl\"},\n                                  {line,116}]},
                         {riak_kv_wm_mapred,pipe_mapred_nonchunked,3,[{file,\"src/riak_kv_wm_mapred.erl\"},{line,260}]},
                         {webmachine_resource,resource_call,3,[{file,\"src/webmachine_resource.erl\"},{line,186}]}]}}
```

After adding a logging call to the code I noticed this in the server log.

```
2013-12-23 21:39:48.357 [error] <0.252.0>@riak_kv_wm_mapred:pipe_mapred_nonchunked:260   [{phase,0},{error,<<"bad_json">>},{input,<<"{ok,{r_object,{<<\"mr_index\">>,<<\"b1\">>},<<\"key_4\">>,[{r_content,{dict,7,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[[<<\"Links\">>]],[],[[<<\"dot\">>|{<<92,176,215,10,82,184,173,140>>,{1,63555053987}}]],[],[],[],[],[],[[<<\"content-type\">>,97,112,112,108,105,99,97,116,105,111,110,47,106,115,111,110],[<<\"X-Riak-VTag\">>,55,51,99,97,74,86,50,100,83,102,65,76,88,56,90,70,85,100,80,67,101,77]],[[<<\"index\">>]],[],[[<<\"X-Riak-Last-Modified\">>|{1387,834787,399263}]],[],[[<<\"...\">>]]}}},...}],...},...}">>}]
```

Notice the `<<\"dot\">>|{<<92,176,215,10,82,184,173,140>>,{1,63555053987}`. Mochijson cannot properly encode the dot in this form. It is my feeling that the dot should not be exposed for JS map-reduce. The function `riak_object_json:jsonify_metadata` needs to be fixed.

### PR DESCRIPTION
**Pull request by rzezeski**
There is no need to encode the dot for JavaScript map-reduce. It is an
internal thing and doesn't need to be exposed.

This fixes #779.

I see 6 eunit failures both on this branch and develop.

### CODE REVIEW

**Comment by russelldb** [comment]
WFM +1. Nice catch. Thanks.

**Comment by russelldb** [comment]
Actually, second thoughts, I think I might have to be smarter and binary encode the dot. What about downgrades? If data is written with a dot, then the node downgraded, this fix won't be there, but the dot still will be.

**Comment by rzezeski** [comment]
Yea, I didn't think of downgrade case. We should revisit this after holidays. Merging for now so tests will work in 2.0.

**Comment by jonmeredith** [comment]
@rzezeski can you open an issue to track?

On Tue, Dec 24, 2013 at 8:17 AM, Ryan Zezeski notifications@github.comwrote:

> Yea, I didn't think of downgrade case. We should revisit this after
> holidays. Merging for now so tests will work in 2.0.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/basho/riak_kv/pull/782#issuecomment-31174740
> .

## 

Jon Meredith
VP, Engineering
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by seancribbs** [comment]
@jonmeredith We've put a known issue in release notes for the downgrade problem.

**Comment by jonmeredith** [comment]
Ok, great. It's good to have in both places - issues get reviewed more
often than release notes.

On Tue, Dec 24, 2013 at 8:41 AM, Sean Cribbs notifications@github.comwrote:

> @jonmeredith https://github.com/jonmeredith We've put a known issue in
> release notes for the downgrade problem.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/basho/riak_kv/pull/782#issuecomment-31175550
> .

## 

Jon Meredith
VP, Engineering
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by jrwest** [comment]
its also been added to the kill bill for true N = 3 safety!

**Pull request merged**
