### PR TITLE
use short-circuit boolean in refercheck setting

### PR DESCRIPTION
**Pull request by joecaswell**

### CODE REVIEW

**Comment by reiddraper** [comment]
Looks good. What do you think about adding in a default in the app.config for this, so that it's easier for people to find?

**Comment by joecaswell** [comment]
That is an excellent idea

**Comment by reiddraper** [comment]
I was thinking in the [app.config template](https://github.com/basho/riak/blob/master/rel/files/app.config), not in app.src.

**Comment by reiddraper** [comment]
had an offline convo, +1 to merge

**Pull request merged**
