### PR TITLE
Bz939 phase backpressure

### PR DESCRIPTION
**Pull request by kevsmith**
This change causes the map phase to batch up outputs before sending them to any downstream phases. The idea here is to reduce the chattiness of a MapReduce job and increase the amount of work done per message.

### CODE REVIEW

**Comment by slfritchie** [comment]
The fix for bz #938 was merged into riak_kv_0.14 on 2010-Dec-23,
and then that release branch was later merged to master by
changeset 502bf67eb5b2c09a4d6ad5f5d41eeed62522eb0a on 2011-Jan-05.

**Comment by jonmeredith** [comment]
If it's in master - shouldn't we close the pull request?

**Comment by slfritchie** [comment]
Kevin had patches for 2 BZs here.  938's is in master, 939's is not (yet).

**Comment by slfritchie** [comment]
Due to the age of this pull request, I've reapplied the patch onto
a new branch called bz939-phase-backpressure-slf based on today's
master branch.  JavaScript systests pass, PHP and Python systests
both fail.

**Comment by slfritchie** [comment]
The PHP and Python tests were broken.  I've patched them with
respective flavors of the bz939-phase-backpressure-slf branch.
Closing.

**Pull request closed without merging**
