### PR TITLE
Make memory backend obey 2i return terms properly

### PR DESCRIPTION
**Pull request by engelsanchez**
Otherwise it might send term/key pairs to an old node, which wouldn't
know what to do with them. Found with verify_2i_mixed_cluster test.

Compare this to similar code in riak_kv_eleveldb_backend.erl

/cc @jaredmorrow @jonmeredith

### CODE REVIEW

**Comment by engelsanchez** [comment]
Found with this riak test by configuring it to pick up 1.2.1 as legacy and the memory backend.

**Comment by engelsanchez** [comment]
Ugh, I meant this: https://github.com/basho/riak_test/pull/489

**Comment by russelldb** [comment]
I need to run basho/riak_test#489 with 1.2.1 as legacy without this patch, then with this patch to verify it works, correct?

**Comment by engelsanchez** [comment]
You could try any release < 1.4 I believe. Anything before return terms should have the same problem.

**Comment by russelldb** [comment]
OK, finally able to get basho/riak_test#489 to fail without this patch, and pass with. So. Plus One. Again.

**Comment by engelsanchez** [comment]
It's déjà vu all over again

**Pull request merged**
