### PR TITLE
Mas i1807 overflowqueues

### PR DESCRIPTION
**Pull request by martinsumner**
Alternative solution to the unbound queue problem (e.g. alternative to https://github.com/basho/riak_kv/pull/1808).

Rather than simply curtailing when size of queue hits an arbitrary limit - overflow to disk at a limit instead.

This solution also refactors the reaper/eraser to use a common behaviour to remove duplication of code.

### CODE REVIEW

**Comment by martinsumner** [comment]
https://github.com/basho/riak_test/pull/1361

**Comment by hmmr** [comment]
The proposed change implements a disk-backed buffer for delete and reap request queues (as opposed to in-memory queues). It is a mitigation against said queues growing and consuming too much memory, and potentially causing OOM conditions on a node, observed when, for example, a node re-joins its cluster after substantial amount of data has been modified/deleted in the cluster, causing massive AAE activity with which the joining node is unable to cope.

I can see all pieces in the flow and I find eunit tests with good coverage, which I can confirm are passing.

One concern that I have is about stale disk_log files: I agree that ["wiping of wrong data"](https://github.com/basho/riak_kv/pull/1809/commits/fee56e5931d67090b8b4407982569b83ac91e3a8) is a valid argument to the contrary; but something still needs to be done to prevent stale files from appearing. What if `riak_kv.eraser_dataroot` and `riak_kv.reaper_dataroot` are placed in a temp (uuid-based) dir, specifically created at node startup, under some `riak_kv.disklog_queue_dir`? Users can then be able to distinguish between the dir currently in use from dirs left behind, and delete them without the need to stop the node.

Other than that, a couple of nits: no need to [++ strings](https://github.com/basho/riak_kv/pull/1809/files#diff-24efacea5e7b7d6be1d68972e4c37eb252e661437b2e6eb25c4cb193e58df103R126), and [lots](https://github.com/basho/riak_kv/pull/1809/files#diff-13190cb1d6b02cf95feecfe576f9c30f09e066b6e1ff102c409d463ba9040d02R96) of [trailing](https://github.com/basho/riak_kv/pull/1809/files#diff-0e69c47b07842327ba0cecd5c2f63c22852b8a0767fd99a3dc8c12b8b1f8d57fR83) [whitespace](https://github.com/basho/riak_kv/pull/1809/files#diff-24efacea5e7b7d6be1d68972e4c37eb252e661437b2e6eb25c4cb193e58df103R151). Bonus points for using a solution from stdlib (disk_log) instead of reinventing it!

**Comment by martinsumner** [comment]
@hmmr With regards to the use of '++', is this a suggestion to use iolists instead, with the improved efficiency?

**Review by hmmr — APPROVED** [review]
I meant to say that `++` between strings is redundant. But that's not important.

**Pull request merged**
