### PR TITLE
 Disambiguate table, bucket, bucket type #29  [JIRA: RTS-420]

### PR DESCRIPTION
**Pull request by macintux**
In conjunction with https://github.com/basho/riak_ql/pull/29, be explicit about the semantics for various bindings.

### CODE REVIEW

**Comment by Basho-JIRA** [comment]
https://github.com/basho/riak_ql/pull/29 

**_[posted via JIRA by Derek Somogyi]**_

**Comment by Basho-JIRA** [comment]
https://github.com/basho/riak_ql/pull/29
https://github.com/basho/riak_kv/pull/1227 

**_[posted via JIRA by Derek Somogyi]**_

**Comment by Basho-JIRA** [comment]
Assigning to [~Mark Allen]] for review.  Hopefully you are able to review this while John Daily is fixing up the Merge Coverage API PRs. 

**_[posted via JIRA by Derek Somogyi]**_

**Comment by jadeallenx** [comment]
Tests pass clean; requires basho/riak_ql#29 to compile though.

:+1:

**Comment by hazen** [comment]
+1 6efed45

**Comment by macintux** [comment]
@borshop merge

**Pull request merged**
