### PR TITLE
add missing aliases

### PR DESCRIPTION
**Pull request by uwiger**
Refers to RIAK-1294; adds missing aliases.

### CODE REVIEW

**Comment by jburwell** [comment]
:+1: 5ff6b89

**Comment by jburwell** [comment]
@borshop merge

**Comment by jburwell** [comment]
@borshop: retry 5ff6b89

**Comment by uwiger** [comment]
@borshop: retry 5ff6b89

**Comment by jburwell** [comment]
@borshop: retry

**Comment by jburwell** [comment]
:+1: 5ff6b89

**Comment by jburwell** [comment]
@borshop: retry 5ff6b89

**Comment by jburwell** [comment]
@borshop merge

**Pull request merged**
