### PR TITLE
Fix PB List Keys to missing bucket type causes crash, hangs client

### PR DESCRIPTION
**Pull request by jburwell**
Per defect #875, list keys and buckets for an undefined bucket type failed to operate as expected.  Listing keys for an undefined bucket type caused a client hang while listing buckets for an undefined bucket type yielded an {ok, []}.  With this patch, both scenarios return {error, no_type}, and do not hang the client waiting for a reply.

This PR requires modifications to the riak_core_coverage_fsm provided by https://github.com/basho/riak_core/pull/594.

### CODE REVIEW

**Comment by seancribbs** [comment]
I don't see why this needs to touch the client/fsm modules. The client API should do the validation.

**Comment by reiddraper** [comment]
Is this 2.0 work? We should apply the 2.0-RC milestone, if so.

**Comment by reiddraper** [comment]
If we go forward with this approach, kindly squash down to a commit or two, please.

**Comment by kellymclaughlin** [comment]
@seancribbs Could you elaborate on your comment? Are you thinking something similar to the solution in https://github.com/basho/riak_api/pull/62?

**Comment by seancribbs** [comment]
@kellymclaughlin Yes, exactly. This is client validation and should be handled before even trying to start the FSM. 

I'm also concerned about unnecessarily removing explicit matches (e.g. [here](https://github.com/basho/riak_kv/pull/955/files#diff-3ac0e13ed171d03a458be62c38f1c065R653)).

**Comment by reiddraper** [comment]
Suppose we should wait for @jburwell to chime in.

**Comment by jburwell** [comment]
In order to properly squash commits, a new branch was required.  Therefore, PR https://github.com/basho/riak_kv/pull/958 was created a replacement.

**Pull request closed without merging**
