### PR TITLE
Use a macro for the param record name

### PR DESCRIPTION
**Pull request by andytill**
Like ?DDL, so that version changes in the record name do not affect the rest of the code.

This is in advance of the DDL upgrade and down work, to ease changes in so I don't have to merge whenever a function head is modified.

### CODE REVIEW

**Comment by hmmr** [comment]
See https://github.com/basho/riak_ql/pull/134#issuecomment-236604068

**Comment by andytill** [comment]
@borshop: retry

**Comment by hmmr** [comment]
+1 73160de

**Comment by hmmr** [comment]
@borshop merge

**Pull request merged**
