### PR TITLE
Ready - TS - Return the timestamp values in the timestamp register.

### PR DESCRIPTION
**Pull request by alexmoore**
Companion PRs: 
basho/riak_pb#163
basho/riak-java-client#574

### CODE REVIEW

**Comment by alexmoore** [comment]
Dialyzer and xref issues go away if building with correct riak_pb branch:

``` bash
$ make xref
...
==> riak_kv (xref)
10:50:56:riak_kv(fixes/am/fix_encode_timestamp_cells) $ echo $?
0

$ make dialyzer
...
done (passed successfully)
==> riak_kv (dialyzer)
10:49:44:riak_kv(fixes/am/fix_encode_timestamp_cells) $ echo $?
0
```

**Comment by hazen** [comment]
Tests pass.

**Comment by hazen** [comment]
:+1: 2ea8edf

**Comment by alexmoore** [comment]
@borshop retry

**Comment by hmmr** [comment]
With https://github.com/basho/riak_pb/pull/165 in, this PR should be passing the xref check.

I have also merged in the e2e/ts, which by this time has incorporated RTS-203 related changes.

The ts_basic (https://github.com/basho/riak_test/pull/929) test passes.

**Comment by hmmr** [comment]
@borshop merge

**Pull request merged**
