### PR TITLE
Better error handling from basho/riak_kv#935

### PR DESCRIPTION
**Pull request by joedevivo**
If this was run on a version of Erlang less than R16B02-basho5 or R16B03, you'd get this error. 

```
(riak@127.0.0.1)1> riak_kv_env:doc_env().
** exception error: bad argument
     in function  erlang:system_info/1
        called as erlang:system_info(ets_limit)
     in call from riak_kv_env:check_erlang_limits/0 (src/riak_kv_env.erl, line 149)
     in call from riak_kv_env:doc_env/0 (src/riak_kv_env.erl, line 48)
```

With this patch, you'll get no error, and this in the logs:

```
2014-05-12 14:52:50.753 [warning] <0.2271.0> riak_kv_env: ETS table count limit cannot be determined on this version of Erlang
```

Of course, if you have the right Erlang, you'll still see this:

```
2014-05-12 14:58:37.119 [info] <0.2266.0> riak_kv_env: ETS table count limit: 256000
```

### CODE REVIEW

**Comment by joedevivo** [comment]
@vinoski take a look at this sometime?

**Comment by joedevivo** [comment]
never forget basho/riak_kv#935

**Comment by vinoski** [comment]
+1

**Comment by joedevivo** [comment]
@reiddraper there's a dialyzer error in here in a file I haven't touched. any ideas?

**Comment by reiddraper** [comment]
@joedevivo it should be fixed in the merge-commit that bors will make. I fixed it in #941.

**Comment by joedevivo** [comment]
@borshop merge https://github.com/basho/riak_kv/commit/2fd180b88f549a8b729e42e0b2df7119b10fdcdc

**Comment by reiddraper** [comment]
@joedevivo fyi, no need to specify the SHA during merge.

**Comment by reiddraper** [comment]
And more than likely that build will end up stale anyway, since #916 will probably land first.

**Comment by seancribbs** [comment]
@borshop: retry

**Pull request merged**
