### PR TITLE
Ajs overload plumbing

### PR DESCRIPTION
**Pull request by andrewjstone**
Process overload for coverage queries and other queries that were previously not handled. Return `{error, mailbox_overload}` when the riak_core_vnode_proxy tells us we are overloaded.

Part of a fix for #753 
Should be merged together with https://github.com/basho/riak_core/pull/513

### CODE REVIEW

**Comment by russelldb** [comment]
I feel you on the whitespace issues, really I do. We had this discussion a while back and I was told not to mix whitespace fixes with functional changes. And now I can see why: it is hard to tell what has changed for what reason.

**Comment by andrewjstone** [comment]
@russelldb I definitely was not trying to make a whitespace point. I just have 'delete-trailing-whitespace' on and that's what happened when I saved the files. I've committed numerous files just like this and this is the first I'm hearing of the recommendation. I can clean this up if necessary, but it still seems like an improvement to me over no change to the whitespace.

**Comment by russelldb** [comment]
@andrewjstone oops. Ok. So sometime ago we had this discussion on hipchat. I only brought it up 'cos I used to have 'delete-trailing-whitespace' as on and that was happened when I saved files. I was all like "it needs doing and it is better than before" but there was wailing, and gnashing of teeth. And Jon was like "turn it off". So that is why I brought it up. But if we're revisiting it then let's do this. And get rid of trailing whitespace and dodgy formatting. Since precedent says it is not a problem, I'm going to turn mine back on, and point to this discussion (I hope you'll back me up.)

**Comment by evanmcc** [comment]
You can change the diff settings to make the review easier (I think that
adding ?w=0 to the url will work), but that said, if we're going to do
this, we all kind of need to do this, and to make an effort to make the
whole codebase whitespace clean to make the default settings minimally
irritating.

**Comment by andrewjstone** [comment]
@russelldb I've got your back. But I also anticipate more gnashing later. Maybe we can fight it out as allies and convince the angry invading hoards of reviewers.

**Comment by andrewjstone** [comment]
@evanmcc Yep that works. I had no idea. Thank you.

**Comment by jrwest** [comment]
fwiw, `git add -i` is also useful when you have `delete-trailing-whitespace` on but don't want to commit the changes. imo, its useful to have proper formatting but we should do it all in on PR in some automated way across all files once. It mucks w/ the commit history/blame/etc otherwise.

**Comment by evanmcc** [comment]
+1 to having this be an automated process, followed by an ongoing
commitment to keeping the codebase clean.

**Comment by andrewjstone** [comment]
Ok. So should I change _this_ PR, or just not do this next time?

**Comment by russelldb** [comment]
My opinion is first offence, let off with a warning (as in don't change this PR, but don't do it next time)

**Comment by andrewjstone** [comment]
Me too. we have better things to do.

**Comment by jonmeredith** [comment]
Since git-blame and github both have options for ignoring white space changes, I care less than i used too.

**Comment by kuenishi** [comment]
I opened a [suggestion and place to discuss code formatting at Riak CS repos](https://github.com/basho/riak_cs/pull/783). If you like, come and discuss please.

**Comment by kellymclaughlin** [comment]
Sorry to disrupt the flow of whitespace bikeshedding, but...

I modified the overload riak_test to use a PB connection instead of the local client for the key and bucket listing requests and noticed that the change to `riak_kv_keys_fsm` and `riak_kv_buckets_fsm` to return an error tuple instead of just the error reason yields results like the following returned from the PB client: 

```
{error,<<"{error,mailbox_overload}">>}}
```

A small change to the `process_stream` function clauses for error handling in `riak_kv_pb_bucket` should fix that up.

Maybe we could also change the test to use the PB client for the requests to exercise that code path and verify the change.

**Comment by kellymclaughlin** [comment]
No regressions in eunit or eqc tests and riak_test testing looks good. Nice job. :+1:

**Pull request merged**
