### PR TITLE
Fix mem backend to honor various settings correctly.

### PR DESCRIPTION
**Pull request by evanmcc**
@angrycub is testing.

test grid spreadsheet (basho-only):
https://docs.google.com/a/basho.com/spreadsheet/ccc?key=0AkSRjImmlw_HdG5TeVZ2dFRtUFpiZjI2YThQRHFGRWc#gid=0

Without this patch, the memory backend can 'run out of space' in that all of its memory is marked as used, while there is plenty of memory available.  Expiry can do similar things.  This patch makes sure that the state tuple is preserved through all vnode actions, as well.

This should be ported to 2.0 prior to the RC.  

cc @reiddraper re #717

### CODE REVIEW

**Comment by reiddraper** [comment]
Added to 2.0-RC milestone and assigned @angrycub as reviewer.

**Comment by reiddraper** [comment]
The build is currently failing with a meck dependency error. Maybe try merging/rebasing with develop?

**Comment by angrycub** [comment]
Testing completed.  Patch performs as expected.

**Comment by evanmcc** [comment]
@reiddraper reid, is was that comment meant for this issue?  This is a 1.4 PR.  The 2.0 version will be slightly different (yay) than the other three or four versions of this that I've done.

**Comment by reiddraper** [comment]
@evanmcc it was, take a look at the build failure: http://buildbot.bos1/builders/test-riak_kv/builds/1321.

**Comment by reiddraper** [comment]
Moving this off of the 2.0 milestone and onto 1.4.9.

**Comment by evanmcc** [comment]
merged despite the kv breakage: it's from rebar issues in core and folsom that should be fixed separately IMO

**Pull request merged**
