### PR TITLE
Add disk stats to `/stats` output to make consistent

### PR DESCRIPTION
**Pull request by russelldb**
As pointed out by @fygrave in #285, `riak-admin status` shows
diak stats, but `/stats` does not. This fixes that.

### CODE REVIEW

**Comment by coderoshi** [comment]
+1 works great, the test failure isn't related to this change.

**Comment by coderoshi** [comment]
Is this still necessary with #428?

**Comment by russelldb** [comment]
Yes. #428 just moves the legacy code to a different module.

**Comment by rzezeski** [comment]
Is there a reason this was never merged?

**Comment by russelldb** [comment]
None that I know of.

**Comment by russelldb** [comment]
Oh wait, probably too late for a release, then forgotten.

**Comment by russelldb** [comment]
oops, fat fingered the close.

**Comment by rzezeski** [comment]
Lazy question, where does the disk id come from?  I see this on OSX

`disk : [{"15365726",1089309792,12},{"5642072",1943949344,2}]`

**Comment by rzezeski** [comment]
Answered my own question.  It comes from `disksup:get_disk_data()`.

Anyways, the PR adresses the issue.  I therefore put a second +1 on this PR.  Please merge this time :)

**Pull request merged**
