### PR TITLE
revert allow_mult default only for untyped (default type) buckets

### PR DESCRIPTION
**Pull request by jrwest**
as discussed.

confbal -- I attempted to update the description for `allow_mult` but am realizing now that this is probably insufficient given all default bucket properties in `riak.conf` only affect untyped buckets and we have yet to decide if "untyped buckets" is in fact what we want to call them.

Before Merge:
- [x] verify test changes are correct and pass
- [ ] CSE +1
- [x] PM +1
- [ ] Have a plan re: testing (specifically `riak_test`) as discussed -- ideally testing both setting values, or at a minimum preserve `allow_mult=true` in tests that have been updated to account for it

### CODE REVIEW

**Comment by jrwest** [comment]
for the reviewer: typed bucket defaults can (unfortunately?) be found [here](https://github.com/basho/riak_core/blob/develop/src/riak_core_bucket_type.erl#L119)

**Comment by seancribbs** [comment]
:+1: on schema tests.

**Comment by gburd** [comment]
I'm not a fan of reverting this to default to "false" :poop:
That said, +1

**Comment by kellymclaughlin** [comment]
:+1:

**Comment by jonmeredith** [comment]
+1 merge - accepting giddyup breakage.  Will need to fix tests to go from beta to rc.

**Pull request merged**
