### PR TITLE
Verify bucket type existence for list keys and buckets operations

### PR DESCRIPTION
**Pull request by jburwell**
Per defect #875, the client hangs when attempting to list keys or buckets for an undefined bucket types.

This fix represents a time/risk compromise for the previous proposed solution which made a deeper change to the riak_core_coverage_fsm -- pushing the check for bucket definition down to the state machine ensuring that all bucket type uses are consistently checked. #965 has been opened to revisit this approach when we have the time to address the issue more holistically.

Supersedes squashes the commits and integrates feedback from [PR 966](https://github.com/basho/riak_kv/pull/966).

/cc @kellymclaughlin @seancribbs @reiddraper

### CODE REVIEW

**Comment by reiddraper** [comment]
Thanks. Waiting for the build to finish, then I'll look over once more, but looks fine on first pass.

**Comment by kellymclaughlin** [comment]
- [X] eunit + eqc
- [X] dialyzer
- [X] xref
- [X] riak_test

**Comment by jburwell** [comment]
@borshop merge

**Comment by seancribbs** [comment]
This is still broken. http://buildbot.bos1/builders/python-client-test/builds/60/steps/make%20test/logs/stdio

**Pull request merged**
