### PR TITLE
Issue/665 retry put coordinator failure

### PR DESCRIPTION
**Pull request by slfritchie**
Addresses #665 

I strongly disagree that the default should be 'off'.  This is Riak 2.0 and is a good time to introduce a behavior change that should've happened many releases ago.

There's a tentative cuttlefish thingie in one of the commit log messages.

### CODE REVIEW

**Comment by slfritchie** [comment]
Suggested reviewers: @russelldb and/or @jrwest.

**Comment by russelldb** [comment]
Ran the dt riak_tests against this patch and they pass. Code looks clean. +1 from me. Thanks Scott!

**Comment by slfritchie** [comment]
@joedevivo It looks like the first Cuttlefish stuff for the riak_kv repo has now merged to `develop`.  I'll mangle together a schema thingie and merge it and the rest of this branch into `develop`.

**Comment by slfritchie** [comment]
Cuttlefish goop added in `develop` by commit 19c472eaf2d1fe9.

**Pull request merged**
