### PR TITLE
.hrl merge in riak_ql fixes, plus filters rewrite for eleveldb

### PR DESCRIPTION
**Pull request by gordonguthrie**
There were dependency problems caused by having two .hrl files in riak_ql which meant that spurious dialyzer warnings were being created. They have been merged, this PR includes the riak_kv side of the house.

In addition the post-query-rewrite filters have to be rewritten in a way that they are consumable at the leveldb end. That change is incorporated here.

### CODE REVIEW

**Comment by andytill** [comment]
I get a build error because riak_ql_sql.hrl is still referenced in riak_kv_pb_timeseries.erl, https://github.com/basho/riak_kv/blob/feature/az/fetch-qry-results/src/riak_kv_pb_timeseries.erl#L4

**Comment by gordonguthrie** [comment]
Its clearly deleted in the file @andytill

**Comment by andytill** [comment]
@gordonguthrie yep nvm, I was looking fetch-qry-results branch.

**Comment by andytill** [comment]
+1 cdaca2cfcff8e062b638eec68a1b2043e66a36b3

**Comment by andytill** [comment]
@borshop merge

**Pull request merged**
