### PR TITLE
Avoid mutator code path when necessary.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Avoid the mutator code path completely when there are no registered
mutators, which prevents the mutators_applied item from being added to
the metadata dictionary when there are no mutators.

@Vagabond @engelsanchez @lordnull

### CODE REVIEW

**Comment by Vagabond** [comment]
Looks good, but have not run the code.

**Comment by lordnull** [comment]
The mutator code path is still hit if the registered mutators list is of length 0. It might be nicer if the registered function returned [] in the case of undefined.

One could even contend that instead of putting that check in the kv code, put it in the mutator code and have mutate_put return early in the case of an empty mutator list.

**Comment by cmeiklejohn** [comment]
Pushed an update which changes the function to `any_registered/0` which returns true or false.  I'd rather not call into mutate_put if we don't have to, which preserves existing behavior.

**Comment by lordnull** [comment]
Eunit tests pass.

Ran this through the repl_reduced risk_test which fails the data_push test in that it creates a sibling. I doubt that's due to this change however.

I would like to have recorded more on the "why" of this. It's not saving a call to metadata (adding one for when there are mutators in fact). It's by-passing the resolver function and just using the metadata last write wins. If the goal was just to avoid adding metadata to the object if no mutators were configured, then I see reason to alter the behavior of the put in mutator; it's not like it's been shipped in a final release.

**Comment by cmeiklejohn** [comment]
The motivation was to avoid a majority of the code in the `riak_kv_mutator` code path, in addition to not modifying the metadata dictionary with the `mutators_applied` entry when no mutators were registered.

**Comment by lordnull** [comment]
I have two main issues that have not been addressed:
1. the existing resolver for getting mutators is ignored for no reason
2. for most enterprise customers, particularly those with repo, this will add a call to the metadata system to get the mutators; i.e. a second call to get the exact same data.

**Comment by cmeiklejohn** [comment]
@lordnull Can you point me to what you mean by 1?

**Comment by lordnull** [comment]
The exported `get` function: https://github.com/basho/riak_kv/blob/52e91f69f08bc8cd16beb4943480e8552336dff1/src/riak_kv_mutator.erl#L87
uses a resolver internally:
https://github.com/basho/riak_kv/blob/52e91f69f08bc8cd16beb4943480e8552336dff1/src/riak_kv_mutator.erl#L150

I have concerns about just using the default resolver for cluster metadata of 'last write wins', so I a merging resolver. If it's not useful or has potential issues in this case, some documentation stating why would be helpful.

**Comment by cmeiklejohn** [comment]
Ah; I see what you mean now.  Thanks.

**Comment by cmeiklejohn** [comment]
"...for most enterprise customers, particularly those with repo, this will add a call to the metadata system to get the mutators; i.e. a second call to get the exact same data."

True, but you could easily argue that for all OSS users, or rather _anyone_ using kv, not enterprise, have an additional call to a function that will perform no action, which is the larger and more common use case.

**Comment by cmeiklejohn** [comment]
Amended commit with new strategy.  Thoughts?

**Comment by lordnull** [comment]
Passes eunit, riak_tests that passed before continue to pass. :+1:

> True, but you could easily argue that for all OSS users, or rather anyone using kv, not enterprise, have an additional call to a function that will perform no action, which is the larger and more common use case.

So which is cheaper: a case statement or an external module function call? Since I don't know, and I'm pretty certain both are faster than querying for the the metadata (and resolving it), it's good enough to merge.

**Comment by cmeiklejohn** [comment]
I'll let @evanmcc handle optimization when he gets to it.

**Pull request merged**
