### PR TITLE
fix some of the easier dialyzer issues

### PR DESCRIPTION
**Pull request by hmmr**
Also, dialyzer.ignore-warnings has been regenerated from the current
dialyzer output, in which entries are now sorted.

### CODE REVIEW

**Comment by macintux** [comment]
Will review

**Comment by macintux** [comment]
Changes look good. Waiting to give a final thumbs up until I can do a fresh build + dialyzer (facing environmental challenges at the moment).

**Comment by hmmr** [comment]
These two are not so trivial, so please have a look.

**Comment by hmmr** [comment]
@jonmeredith going to see to riak_core, too, just want to finish riak_kv (which depends on riak_pb).

**Comment by hmmr** [comment]
@borshop retry

**Comment by hmmr** [comment]
@borshop retry

**Comment by hmmr** [comment]
A couple of months ago I created this janitor branch, off then-`develop`, and pushed some commits, which got +1'ed, and which I was remiss to merge in time. Instead, I piled more commits onto it, and then got preoccupied by other stuff. This resulted in it collecting dust since.

Per @macintux suggestion, I have rebased this branch onto the current branch 2.1, reset it to the last commit that received a +1 (from @jonmeredith) and pushed with force. The idea is to merge it this far, and add the rest of commits later for eventual inspection.

On a push -f, github chose to redisplay a ton of comments from commits in a previously merged branch, which is confusing and makes one scroll-weary. To unconfuse things, this is how these commits chain up to the 2.1 tip:
screenshot1

**Comment by hmmr** [comment]
Oh, this PR is still into develop, so scrapping it and closing.

**Pull request closed without merging**
