### PR TITLE
Cover enabled is causing problems with eunit tests failing under rebar

### PR DESCRIPTION
**Pull request by macintux**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Please open PRs for the 2.0 and 2.1 branches.

**Comment by macintux** [comment]
#1125 for 2.0, #1126 for 2.1.

**Comment by cmeiklejohn** [comment]
:+1: 9473567

**Comment by cmeiklejohn** [comment]
@borshop merge

**Comment by cmeiklejohn** [comment]
Force merge, given bors isn't going to give this one the :+1:.

**Pull request merged**
