### PR TITLE
add riak_kv_vnode:handle_overload_info/2

### PR DESCRIPTION
**Pull request by andrewjstone**

### CODE REVIEW

**Comment by andrewjstone** [comment]
Requires basho/riak_core#605 to fix #986

**Comment by kellymclaughlin** [comment]
- [x] Eunit and eqc
- [x] Dialyzer
- [x] xref
- [x] code inspection

**Comment by kellymclaughlin** [comment]
Nice work, :+1:

**Comment by andrewjstone** [comment]
@borshop merge

**Pull request merged**
