### PR TITLE
Move metadata settings to advanced level.

### PR DESCRIPTION
**Pull request by evanmcc**
move md cache cuttlefish tunings into advanced so people are less
likely to play with it.  as written it is hard to make it improve
performance in a predictable way.
- [x] Eng +1
- [ ] PM +1
- [ ] CSE +1

### CODE REVIEW

**Comment by lordnull** [comment]
Same generated value before and after change, only difference is the metadata_cache_size is not visible in the riak.conf file.

:+1:

**Comment by seancribbs** [comment]
This did not get CSE/PM approval. :frowning:

**Comment by evanmcc** [comment]
_shrug_

It should have never been in there in the first place, since the feature
was never fully baked.  I'll be sure to ping everyone next time.

**Comment by jonmeredith** [comment]
It was discussed on the Core/KV mumble and I think GregB was there.  But I could have remembered wrong.

@seancribbs did it break something?

**Comment by seancribbs** [comment]
@jonmeredith Nope, just wanted to be sure the process was clear.

**Pull request merged**
