### PR TITLE
RIAK-1802

### PR DESCRIPTION
**Pull request by lukebakken**
Address permissions issues around `riak_kv.get_preflist`
- Could not grant this permission as it was not part of the `permissions` list.
- When permission fails, error message would not get printed due to `badarg`. PBC `decode` function did not return the correct value.

See basho/riak_core#706 (RIAK-1602) (RIAK-1802)

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
@lukebakken This is passing locally for me and looks correct to me.  Any known reason the builder is just failing in the midst of this?

**Comment by zeeshanlakhani** [comment]
:+1: 10c85013e1b9e38838e43d8a20ec0ae763ad62a3 ^^ @lukebakken

**Comment by zeeshanlakhani** [comment]
@lukebakken tests pass for pb and i've tested via curl and such.

**Comment by lukebakken** [comment]
Awesome :+1: then

**Comment by lukebakken** [comment]
:+1: 10c8501

**Comment by lukebakken** [comment]
:+1: e61e6b655669fb5cee0422348671c37ea12f78ab

**Comment by zeeshanlakhani** [comment]
hmm... @bors! 

:+1: e61e6b655669fb5cee0422348671c37ea12f78ab

**Comment by lukebakken** [comment]
@borshop merge

**Pull request merged**
