### PR TITLE
use tuple modules instead of parameterized modules

### PR DESCRIPTION
**Pull request by vinoski**
Erlang R16, coming soon, will do away with parameterized modules (see Issue
4 under http://www.erlang.org/news/35 for details). Change riak_client to
use tuple modules instead, since they will continue to be supported in R16
and beyond. These changes are backward compatible.

### CODE REVIEW

**Comment by engelsanchez** [comment]
Steve: any reason why you went with passing the client as the last parameter vs as the first? That would make it the same as riakc_pb_socket. Not that Erlang libraries are famous for consistency in that area, but...

**Comment by vinoski** [comment]
The parameterized module feature always passed its module argument as the last argument. I therefore made the tuple module the last argument as well to keep it completely backwards compatible for existing callers.

**Comment by engelsanchez** [comment]
So they passed it as the last argument behind the curtains, blergh. Too bad. We'll get a lot of flak for this client incompatibility in the future :(

**Comment by engelsanchez** [comment]
For future readers of this thread: my comments above were due to my not knowing what "tuple modules" are. Total non-issue.

**Comment by cmeiklejohn** [comment]
@engelsanchez any outstanding concerns here?  also, how far did you get with the testing of this so I know where to continue?

**Comment by engelsanchez** [comment]
@cmeiklejohn This was a total drive by comment, sorry. Start from scratch

**Comment by cmeiklejohn** [comment]
:+1: looks good, builds and passes eunit.

**Comment by evanmcc** [comment]
have rebased this and pulled it into #602.

**Pull request closed without merging**
