### PR TITLE
Add trace statements to get/put FSMs & vnode

### PR DESCRIPTION
**Pull request by Vagabond**
Also, add new 'trace' option to riak_client to write get/put traces to a
file.

### CODE REVIEW

**Comment by slfritchie** [comment]
Andrew, looks like some PR shepherding hasn't happened in a while.  What would you like to see done with this PR?

**Comment by slfritchie** [comment]
Ping?

**Comment by jrwest** [comment]
I would be curious how this interacts w/ https://github.com/basho/riak_kv/pull/734

**Comment by evanmcc** [comment]
dunno.  I can try to update the PR to work with #734 current code if people
think that it's of value and should be in 2.0.

**Comment by bsparrow435** [comment]
I like this functionality and would like to move it to use the new lager sinks introduced in lager 3.0. Assigning to myself to add this to the massive log addition we're going to do in 2.2.x.

**Comment by yorkshire-steve** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
