### PR TITLE
Feature zl add expanded is crdt [JIRA: RIAK-2531]

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
Smarter DT/CRDT check ^^ @angrycub @JeetKunDoug and also backtracking it to 2.0.

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
create jira issue (a neverending story)

**Comment by bsparrow435** [comment]
+1 812915c1aaf368a4141f09ba8e4a5ebc5d08fcf0

**Comment by bsparrow435** [comment]
+1 0a1155c7ebe2de85991941474841b9a73f2377b1

**Comment by zeeshanlakhani** [comment]
@borshop merge

**Pull request merged**
