### PR TITLE
RTS-1149: Add missing query_insert to riak_kv_ts_api:api_call_to_perm/1

### PR DESCRIPTION
**Pull request by hazen**

### CODE REVIEW

**Comment by andytill** [comment]
Should we differentiate between put and insert?

**Comment by hazen** [comment]
I think so. We differentiate between get and query, right?

**Comment by andytill** [comment]
We do but I don't think it is correct, can't think of any use cases where someone would need put privileges but not insert privileges.

**Comment by hazen** [comment]
My understanding based on @ph07's comments in today's mumble that we want to keep this level of granularity

**Comment by hazen** [comment]
Naturally we also need #1443

**Comment by hmmr** [comment]
+1 171249c

**Comment by macintux** [comment]
Rejecting this approach in favor of #1441. Will close when testing is done

**Comment by hazen** [comment]
@macintux Awesome time for me to grab lunch.  We need to discuss now.

**Pull request closed without merging**
