### PR TITLE
Move the DDL code from riak_kv to riak_ql and add a rebar dependency

### PR DESCRIPTION
**Pull request by gordonguthrie**
This is the counter party to this commit:
https://github.com/basho/riak_ql/commit/14fc5da78b3f580f76283e2a586a8d965242518e

### CODE REVIEW

**Comment by bkerley** [comment]
+1 bff8681 with the caveat that riak_ql doesn't compile on the branch it's fetching

**Comment by andytill** [comment]
+1

**Comment by andytill** [comment]
+1 bff8681

**Comment by gordonguthrie** [comment]
@borshop merge

**Comment by andytill** [comment]
+1 bcf3ebd29db53ac7a9477674f75f33af9b603900

**Comment by andytill** [comment]
+1 bcf3ebd29db53ac7a9477674f75f33af9b603900

**Comment by gordonguthrie** [comment]
@borshop merge

**Pull request merged**
