### PR TITLE
Remove ability for clients to modify bucket types.

### PR DESCRIPTION
**Pull request by seancribbs**
See also basho/riak_pb#62 and basho/riak_api#42.

### CODE REVIEW

**Comment by jrwest** [comment]
I was chatting w/ @rzezeski about this yesterday and he made my opinion waver a bit. We want to remove these APIs because we won't expose them in the client unless we can do so for the full set of bucket type operations (we are currently missing create and activate). However, the reason for not exposing certain ones is because Security. In some cases a user may care more about programmatic use of these operations over security and we can give them that option by writing APIs for the missing operations but only allowing them to succeed when security is disabled (I think that would be safe,  @Vagabond?). Curious to get other people's thoughts on this.

**Comment by Vagabond** [comment]
Yes, we could tie it to some non-existant permission or something.

I don't mind doing it like this as long as I don't have to implement ACL management over the riak client API (at least not yet).

**Comment by lafka** [comment]
@jrwest can you elaborate on the potential security issues of exposing API for creating and updating bucket types?

I would like to have the ability to update bucket type properties programmatic, same as I would like to have the ability to update the properties of individual buckets.

**Comment by seancribbs** [comment]
@jrwest @Vagabond @rzezeski I know we've been over-and-over this topic, but I'd love to discuss again post-RICON.

**Comment by jrwest** [comment]
@lafka i'm going to defer to @Vagabond on the details. We are discussing supporting the API when security is disabled for now.

@seancribbs happy to chat about it whenever.

**Comment by slfritchie** [comment]
Pulling PRs out of the freezer ... this doesn't have a milestone assigned to it?  Is that by design?

**Comment by seancribbs** [comment]
@slfritchie We will have to decide this by 2.0, it is contentious and should be one-way-or-t'other. @jrwest @Vagabond shall we reopen this debate?

**Comment by jrwest** [comment]
Yea it would be great to re-open it and get something in the API w/o security on in my opinion. I guess there is just the matter of time...What do you think @seancribbs @Vagabond?

**Comment by seancribbs** [comment]
@jrwest Let's plan to discuss soon. Monday work?

**Comment by jrwest** [comment]
works for me

**Comment by seancribbs** [comment]
Had a mumble about it today, the consensus was:
1. Remove the "reset bucket type" operation from the API
2. Omit some of the functionality from client libraries until the API is complete with all features.

As a result, I'm closing this PR and its buddies in favor of new ones that accomplish point 1.

**Pull request closed without merging**
