### PR TITLE
Restore the empty struct that was streamed out in the beginning of a list

### PR DESCRIPTION
**Pull request by rustyio**
Recent refactoring to HTTP interface caused Java client to fail.

The _old_ listkeys returned this:

```
» curl "http://localhost:8098/riak/test_stream_keys?keys=stream"
{}{"keys":["key7"]}{"keys":["key13"]}{"keys":["key4","key2"]}{"keys":["key14"]}{"keys":["key8"]}{"keys":["key10"]}{"keys":["key0","key1","key11"]}{"keys":["key19"]}{"keys":["key18"]}{"keys":["key12"]}{"keys":["key17"]}{"keys":["key9"]}{"keys":"key6","key16","key3"]}{"keys":["key15"]}{"keys":["key5"]}{"keys":[]}% 
```

The _new_ listkeys returns this:

```
» curl "http://localhost:8098/riak/test_stream_keys?keys=stream"
{"keys":["key7"]}{"keys":["key13"]}{"keys":["key4","key2"]}{"keys":["key14"]}{"keys":["key8"]}{"keys":["key10"]}{"keys":["key0","key1","key11"]}{"keys":["key19"]}{"keys":["key18"]}{"keys":["key12"]}{"keys":["key17"]}{"keys":["key9"]}{"keys":["key6","key16","key3"]}{"keys":["key15"]}{"keys":["key5"]}{"keys":[]}%                                                                                                       
```

Notice that the old version has an empty result at the start of the result set.

This pull request restores the old behavior with the empty result set. After this change, all tests pass on the Java client.

Still investigating the root cause.

Test with:

```
git@github.com:basho/riak-java-client.git
mvn clean
mvn -Pitest verify
```

Should see 89 passing tests.

### CODE REVIEW

**Comment by dizzyd** [comment]
Maybe I'm missing something, but doesn't it seem better NOT to always
have that empty set at the beginning?

On Fri, Aug 5, 2011 at 6:51 PM, rustyio
reply@reply.github.com
wrote:

**Comment by beerriot** [comment]
Judging by this comment
https://github.com/basho/riak-java-client/blob/master/src/main/java/com/basho/riak/client/response/BucketResponse.java#L74
that "empty struct" was supposed to be the bucket properties.  So, perhaps it should be `mochijson:encode({struct, BucketPropsJson})` instead.

**Comment by rustyio** [comment]
Yep, @beerriot is correct. Looks like I started down the road of making this completely backward compatible, then failed to finish. Updated code to use BucketPropsJson in the right places, see latest commit.

Tested by comparing master branch against 0.14.2 branch:

```
# With 'master' branch...
curl "http://localhost:8098/riak/foo?keys=true"
{"props":{"name":"foo","allow_mult":false,"basic_quorum":true,"big_vclock":50,"chash_keyfun":{"mod":"riak_core_util","fun":"chash_std_keyfun"},"dw":"quorum","last_write_wins":false,"linkfun":{"mod":"riak_kv_wm_link_walker","fun":"mapreduce_linkfun"},"n_val":3,"notfound_ok":false,"old_vclock":86400,"postcommit":[],"pr":0,"precommit":[],"pw":0,"r":"quorum","rw":"quorum","small_vclock":10,"w":"quorum","young_vclock":20},"keys":[]} 

# Version 0.14.2...
curl "http://localhost:8098/riak/foo?keys=true"
{"props":{"name":"foo","n_val":3,"allow_mult":false,"last_write_wins":false,"precommit":[],"postcommit":[],"chash_keyfun":{"mod":"riak_core_util","fun":"chash_std_keyfun"},"linkfun":{"mod":"riak_kv_wm_link_walker","fun":"mapreduce_linkfun"},"old_vclock":86400,"young_vclock":20,"big_vclock":50,"small_vclock":10,"r":"quorum","w":"quorum","dw":"quorum","rw":"quorum"},"keys":[]}


# With 'master' branch...
curl "http://localhost:8098/riak/foo?keys=stream"
{"props":{"name":"foo","allow_mult":false,"basic_quorum":true,"big_vclock":50,"chash_keyfun":{"mod":"riak_core_util","fun":"chash_std_keyfun"},"dw":"quorum","last_write_wins":false,"linkfun":{"mod":"riak_kv_wm_link_walker","fun":"mapreduce_linkfun"},"n_val":3,"notfound_ok":false,"old_vclock":86400,"postcommit":[],"pr":0,"precommit":[],"pw":0,"r":"quorum","rw":"quorum","small_vclock":10,"w":"quorum","young_vclock":20}}{"keys":[]}

# Version 0.14.2...
curl "http://localhost:8098/riak/foo?keys=stream"
{"props":{"name":"foo","n_val":3,"allow_mult":false,"last_write_wins":false,"precommit":[],"postcommit":[],"chash_keyfun":{"mod":"riak_core_util","fun":"chash_std_keyfun"},"linkfun":{"mod":"riak_kv_wm_link_walker","fun":"mapreduce_linkfun"},"old_vclock":86400,"young_vclock":20,"big_vclock":50,"small_vclock":10,"r":"quorum","w":"quorum","dw":"quorum","rw":"quorum"}}{"keys":[]}


# With 'master' branch...
curl "http://localhost:8098/riak/foo?keys=true&props=false"
{"keys":[]}

# Version 0.14.2...
curl "http://localhost:8098/riak/foo?keys=true&props=false"
{"keys":[]}


# With 'master' branch...
curl "http://localhost:8098/riak/foo?keys=stream&props=false"
{}{"keys":[]}

# Version 0.14.2...
curl "http://localhost:8098/riak/foo?keys=stream&props=false"
{}{"keys":[]}


# With 'master' branch...
curl "http://localhost:8098/buckets/foo/keys?keys=true"
{"keys":[]}

# With 'master' branch...
curl "http://localhost:8098/buckets/foo/keys?keys=stream"
{"keys":[]}
```

**Comment by beerriot** [comment]
+1 merge, thanks!

**Pull request merged**
