### PR TITLE
Implemented Riak TS SQL "WHERE IS [NOT] NULL"

### PR DESCRIPTION
**Pull request by paegun**
- implemented Riak TS SQL "WHERE IS [NOT] NULL".

### CODE REVIEW

**Comment by hmmr** [comment]
+1

**Comment by hmmr** [comment]
49dfaf6 +1

**Comment by hazen** [comment]
:+1: 49dfaf6

**Comment by hmmr** [comment]
+1 49dfaf6

**Comment by hazen** [comment]
@borshop merge

**Pull request merged**
