### PR TITLE
Edoc cleanup

### PR DESCRIPTION
**Pull request by reiddraper**
## Fix Edoc generation errors
- See basho/tools.mk#5 for notes on the new tools.mk version
- Fixes all Edoc syntax errors

`rm -rf doc && make docs; echo $?` should now return `0`.

### CODE REVIEW

**Comment by reiddraper** [comment]
You have any preference in whether I add some more commits to this branch to fix the review issues, or just rewrite the commits?

**Comment by macintux** [comment]
+1 with the above changes

**Comment by reiddraper** [comment]
Review feedback re-written in 8f424a717f8faef59f2925fb918899eb141c3494.

**Comment by macintux** [comment]
:+1: 86f8af8

**Comment by reiddraper** [comment]
@borshop merge

**Pull request merged**
