### PR TITLE
Fix use of fsm timeouts in 2i AAE

### PR DESCRIPTION
**Pull request by engelsanchez**
Joe pointed out some problems with FSM time outs in this code. It is
possible to set a timeout for the next FSM state, then receive a message
passed to handle_info and lose that timeout if not set again. Basically,
they are useless.
Refactored code to use gen_fsm:send_event_after() instead and managed
timer for the AAE pid request manually.
Also, a zero timeout transition was avoided by refactoring the code
around the next_partition state, which is now a simple function
directly executed from other states.
Also, if a request for an AAE pid every failed, the whole process would
have died silently. Instead, that is handled now like any other
partition error. So 2i AAE can happily go finishing the other
partitions.

### CODE REVIEW

**Comment by jtuple** [comment]
Wanted to test that our theory about missing hashtree pid responses leading to the stall. Went ahead and modified code on 1.4 branch:

``` diff
diff --git a/src/riak_kv_2i_aae.erl b/src/riak_kv_2i_aae.erl
index f4c6433..d5c90b4 100644
--- a/src/riak_kv_2i_aae.erl
+++ b/src/riak_kv_2i_aae.erl
@@ -158,7 +158,12 @@ next_partition(timeout, State=#state{remaining=[]}) ->
     {stop, normal, State};
 next_partition(timeout, State=#state{remaining=[Partition|_]}) ->
     ReqId = make_ref(),
-    riak_kv_vnode:request_hashtree_pid(Partition, {fsm, ReqId, self()}),
+    case random:uniform(100) > 80 of
+        true ->
+            lager:info("Dropping request_hashtree_pid");
+        false ->
+            riak_kv_vnode:request_hashtree_pid(Partition, {fsm, ReqId, self()})
+    end,
     {next_state, wait_for_aae_pid, State#state{aae_pid_req_id=ReqId}, ?AAE_PID_TIMEOUT}.

 %% @doc Waiting for vnode to send back the Pid of the AAE tree process.
```

Then, ran `verify_2i_aae` test. Lo and behold we end up with the following in `console.log` which stalls well past the 30 second AAE pid timeout:

```
2014-02-14 17:13:40.817 [info] <0.12605.0>@riak_kv_2i_aae:repair_partition:243 Acquired lock on partition 388211372416021087647853783690262677096107081728
2014-02-14 17:13:40.817 [info] <0.12605.0>@riak_kv_2i_aae:repair_partition:245 Repairing indexes in partition 388211372416021087647853783690262677096107081728
2014-02-14 17:13:40.817 [info] <0.12605.0>@riak_kv_2i_aae:create_index_data_db:310 Creating temporary database of 2i data in ./data/anti_entropy/2i/tmp_db
2014-02-14 17:13:40.879 [info] <0.12605.0>@riak_kv_2i_aae:create_index_data_db:347 Grabbing all index data for partition 388211372416021087647853783690262677096107081728
2014-02-14 17:13:40.895 [info] <0.12605.0>@riak_kv_2i_aae:create_index_data_db:361 Grabbed 114 index data entries from partition 388211372416021087647853783690262677096107081728
2014-02-14 17:13:40.895 [info] <0.12605.0>@riak_kv_2i_aae:build_tmp_tree:434 Building tree for 2i data on disk for partition 388211372416021087647853783690262677096107081728
2014-02-14 17:13:40.957 [info] <0.12605.0>@riak_kv_2i_aae:build_tmp_tree:464 Done building temporary tree for 2i data with 114 entries
2014-02-14 17:13:40.957 [info] <0.12605.0>@riak_kv_2i_aae:do_exchange:482 Reconciling 2i data
2014-02-14 17:13:41.015 [info] <0.12605.0>@riak_kv_2i_aae:do_exchange:517 Found 114 differences
2014-02-14 17:13:41.066 [info] <0.12605.0>@riak_kv_2i_aae:repair_partition:274 Finished repairing indexes in partition 388211372416021087647853783690262677096107081728
2014-02-14 17:13:41.066 [info] <0.12580.0>@riak_kv_2i_aae:next_partition:163 Dropping request_hashtree_pid
```

And, eventually, the test fails as we say in Giddyup:

```
17:13:40.586 [info] Wait for repair process to finish
17:16:40.587 [error] Timed out (180000ms) waiting for 2i AAE repair process
17:16:40.587 [warning] verify_2i_aae failed: {{assertEqual_failed,[{module,verify_2i_aae},{line,183},{expression,"aae_2i_repair_timeout"},{expected,aae_2i_repair_complete},{value,aae_2i_repair_timeout}]},[{verify_2i_aae,'-run_2i_repair/1-fun-4-',1,[{file,"tests/verify_2i_aae.erl"},{line,183}]},{verify_2i_aae,check_lost_objects,4,[{file,"tests/verify_2i_aae.erl"},{line,97}]},{verify_2i_aae,confirm,0,[{file,"tests/verify_2i_aae.erl"},{line,50}]}]}
17:16:40.587 [error] Error in process <0.88.0> on node 'riak_test@127.0.0.1' with exit value: {{assertEqual_failed,[{module,verify_2i_aae},{line,183},{expression,"aae_2i_repair_timeout"},{expected,aae_2i_repair_complete},{value,aae_2i_repair_timeout}]},[{verify_2i_aae,'-run_2i_repair/1-fun-4-',1,[{file,"test... 
```

Looks like our theory was correct. Alright, so on to this branch. Same diff/etc.

```
2014-02-14 17:26:23.457 [info] <0.12599.0>@riak_kv_2i_aae:repair_partition:292 Finished repairing indexes in partition 388211372416021087647853783690262677096107081728
2014-02-14 17:26:23.457 [info] <0.12574.0>@riak_kv_2i_aae:next_partition:166 Dropping request_hashtree_pid
2014-02-14 17:26:53.459 [info] <0.14440.0>@riak_kv_2i_aae:repair_partition:261 Acquired lock on partition 913438523331814323877303020447676887284957839360
<snip>
2014-02-14 17:26:53.726 [info] <0.14440.0>@riak_kv_2i_aae:repair_partition:292 Finished repairing indexes in partition 913438523331814323877303020447676887284957839360
2014-02-14 17:26:53.726 [info] <0.14468.0>@riak_kv_2i_aae:repair_partition:261 Acquired lock on partition 936274486415109681974235595958868809467081785344
<snip>
2014-02-14 17:26:54.017 [info] <0.14468.0>@riak_kv_2i_aae:repair_partition:292 Finished repairing indexes in partition 936274486415109681974235595958868809467081785344
2014-02-14 17:26:54.017 [info] <0.14482.0>@riak_kv_2i_aae:repair_partition:261 Acquired lock on partition 1347321821914426127719021955160323408745312813056
<snip>
2014-02-14 17:26:54.286 [info] <0.14482.0>@riak_kv_2i_aae:repair_partition:292 Finished repairing indexes in partition 1347321821914426127719021955160323408745312813056
2014-02-14 17:26:54.286 [info] <0.12574.0>@riak_kv_2i_aae:next_partition:166 Dropping request_hashtree_pid
2014-02-14 17:27:24.287 [info] <0.16338.0>@riak_kv_2i_aae:repair_partition:261 Acquired lock on partition 342539446249430371453988632667878832731859189760
<snip>
```

So, happily dropping requests, timing out, and moving on to next partition. Yay! We probably should do a `lager:info` when we timeout though to make logs more clear.

Only issue I see is that we don't handle the new error message. Test still fails because of that:

```
2014-02-14 17:32:36.652 [error] <0.12574.0> gen_fsm riak_kv_2i_aae in state wait_for_aae_pid terminated with reason: no function clause matching riak_kv_2i_aae:to_simple_partition_result({error,no_aae_pid}) line 567
2014-02-14 17:32:36.652 [error] <0.12574.0> CRASH REPORT Process riak_kv_2i_aae with 0 neighbours exited with reason: no function clause matching riak_kv_2i_aae:to_simple_partition_result({error,no_aae_pid}) line 567 in gen_fsm:terminate/7 line 611
```

**Comment by engelsanchez** [comment]
The last fix should address the issue @jtuple found. It also adds error logging when AAE tree pid requests go wrong. Tested by hacking riak_kv_vnode to either drop requests to get a tree id or returning an error tuple.

**Comment by jtuple** [comment]
After the latest commits, things perform as I'd expect. So, +1 on this change. However, the `verify_2i_aae` test now fails anytime a requested pid is dropped (tested using similar diff as before). We should probably update the `riak_test` to differentiate between successful repair and failed repair, so that we don't have non-deterministic CI failures. We already know the test sometimes drops pid requests, because that started this entire investigation/fix.

**Comment by engelsanchez** [comment]
Yes, I agree with you @jtuple. I believe this should fix 2i AAE getting blocked in the real world and report if that race happens. Let's talk next week to help me figure out the best way to make the test more robust, or whether some other protection in the code might be needed to avoid that happening too often (was this maybe related to overload dropping messages? what else could cause it? etc, etc).

**Pull request merged**
