### PR TITLE
Implement AAE-based ensemble syncing

### PR DESCRIPTION
**Pull request by jtuple**
This is the sibling pull-request for basho/riak_ensemble#14

This builds on #887, which has not yet been merged to `develop`, so this pull-request was created against the `jdb-ensemble-overhaul` branch. Both branches will be merged to `develop` after review.

---

This commit updates riak_kv to work with the new ensemble syncing behavior added to riak_ensemble. The purpose of peer syncing is to detect and repair corrupted/missing ensemble backend data.

For riak_kv_ensemble_backend, syncing is implemented using AAE. Anytime a vnode is restarted it is considered untrusted until the vnode performs AAE exchange with a majority of sibling vnodes.

To support AAE syncing, riak_kv_vnode was extended with a new ensemble_repair command and the riak_kv_exchange_fsm was extended to use this command to repair consistent keys. This change is needed because consistent data does not yet support read repair. Likewise, even when consistent data supports read repair, it will only do so when a given ensemble is stable. However, syncing is required to operate even when an ensemble is not stable (eg. peers may be required to sync before they can proceed to elect a leader).

### CODE REVIEW

**Comment by andrewjstone** [comment]
This code looks good. Just needs testing.

**Comment by andrewjstone** [comment]
All 3 ensemble basic riak_tests passed. Just waiting on the sync test to drop from @jtuple and pass.

**Comment by jtuple** [comment]
Just pushed riak_tests: basho/riak_test#573

**Comment by andrewjstone** [comment]
:+1:

**Comment by jtuple** [comment]
Merged to develop in c4dacc551f

**Pull request merged**
