### PR TITLE
Added memory % used total and memory % used by erlang to kv stats.

### PR DESCRIPTION
**Pull request by massung**

### CODE REVIEW

**Comment by massung** [comment]
Some whitespace changes thanks to Emacs. Use ?w=1 in the PR url to ignore them.

**Comment by dreverri** [comment]
How does this differ from get_memory_data()?
https://github.com/basho/riak_kv/blob/master/src/riak_kv_stat.erl#L663

**Comment by massung** [comment]
Good question. On the surface, they appear to be the same. In fact, using get_memory_data() instead, it looks like I could cut out a few proplists:get_value calls and a 1.0 - operation, so I'll make that change. 

As for why I can't use mem_stats() to get the same data, I need this to be output with the regular stats query, and sadly, those use the same tuple keys as what the erlang memory stats use (memory_total would have dual meanings). 

Do you think non-% numbers in the output would be more useful?

**Comment by massung** [comment]
Nevermind. I see that mem_stats() is actually output along with everything else as well in the stats. Closing this PR as everything I need is already there.

Thanks for pointing it out, Dan!

**Pull request closed without merging**
