### PR TITLE
keys_fsm_eqc intermittently fails

### PR DESCRIPTION
**Pull request by reiddraper**
Sha: aa0ae89f4901877b2b08136f8b58de91a2db23cd

So far I've only been able to make this fail by running the entire suite via `make test`. I have _not_ yet been able to make it fail by only running the suite, `./rebar eunit suites=keys_fsm_eqc skip_deps=true`. It only fails some of the runs. Here is the counterexample:

```
module 'keys_fsm_eqc'
  keys_fsm_eqc:49: eqc_test_...Failed! Reason:
{'EXIT',{{badmatch,{error,precommit_fail}},
         [{keys_fsm_eqc,'-prop_basic_listkeys/0-lc$^1/1-1-',3,
                        [{file,"test/keys_fsm_eqc.erl"},{line,76}]},
          {keys_fsm_eqc,'-prop_basic_listkeys/0-fun-3-',6,
                        [{file,"test/keys_fsm_eqc.erl"},{line,76}]}]}}
After 1 tests.
{4115210543,<<"N">>,none,1,546,36852}
Shrinking...(3 times)
Reason:
{'EXIT',{{badmatch,{error,precommit_fail}},
         [{keys_fsm_eqc,'-prop_basic_listkeys/0-lc$^1/1-1-',3,
                        [{file,"test/keys_fsm_eqc.erl"},{line,76}]},
          {keys_fsm_eqc,'-prop_basic_listkeys/0-fun-3-',6,
                        [{file,"test/keys_fsm_eqc.erl"},{line,76}]}]}}
{4115210543,<<" ">>,none,1,10,10000}
*failed*
in function keys_fsm_eqc:'-eqc_test_/0-fun-3-'/1 (test/keys_fsm_eqc.erl, line 49)
**error:{assertEqual_failed,[{module,keys_fsm_eqc},
                     {line,49},
                     {expression,"quickcheck ( numtests ( ? TEST_ITERATIONS , ? QC_OUT ( prop_basic_listkeys ( ) ) ) )"},
                     {expected,true},
                     {value,false}]}
```

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
Maybe it's time to finally put a nail in this test. First we need to add some testing to the riak_test that is currently lacking and then I think we can remove this test.

**Comment by kellymclaughlin** [comment]
#649 has discussion about removal and highlights some things to consider adding to the riak_test prior to removing this, but perhaps we can make time for that now.

**Comment by kellymclaughlin** [comment]
Engel already had a placeholder issue for this. I've moved it to the 2.0RC milestone: https://github.com/basho/riak_test/issues/372

**Comment by reiddraper** [comment]
I've turned this issue into a PR, with the test removed.

**Comment by kellymclaughlin** [comment]
I'm actively working on augmenting the riak_test to cover the missing areas highlighted in #649 so :+1: to merge.

**Pull request merged**
