### PR TITLE
Add skipped_repairs stat.

### PR DESCRIPTION
**Pull request by uwiger**
lager message on stat_update_error changed from error to debug.

### CODE REVIEW

**Comment by jburwell** [comment]
@ulf Does skipped_read_repair stat need to be added the legacy stat map in both riak_kv and riak_core?

**Comment by uwiger** [comment]
@jburwell, yes if you want to report it via both HTTP (riak_kv) and riak-admin status (riak_core).

**Comment by jburwell** [comment]
Previously, we have collected the skipped_read_repairs stat, but not provided in `riak-admin status` or via the HTTP endpoint.  In discussing with @bsparrow435, it seems reasonable to add it as part of this bug fix.

/cc @uwiger

**Comment by jburwell** [comment]
:+1: d23478e

**Comment by jburwell** [comment]
@borshop merge

**Pull request merged**
