### PR TITLE
Rework riak-admin test to support local and cluster options

### PR DESCRIPTION
**Pull request by bsparrow435**
Add `riak:client_test(cluster)` which creates a list of bucket/keys which maps to all preflists in the ring.  Each keys does a get/put/get cycle with R=quorum and W|DW=N through a client connected to the local node. 

The list of `{Preflist,{Bucket,Key}}` is saved to `Bucket: <<"__riak_client_test__">> Key: <<"list">>` for future use. This is ok because of consistent hashing as long as the n_val is not changed on the <<"**riak_client_test**">> bucket or the ring_size is not changed. I plan on adding logic to check if the ring_size has been changed(something like check the length of the stored list versus the length of `riak_core_ring:all_preflists(Ring, NValue).`)

Legacy functionality is not changed. The local node test still uses a static key that may or may not map to the local node. I am planning on changing this soon.

### CODE REVIEW

**Comment by bsparrow435** [comment]
basho/riak#307

**Comment by slfritchie** [comment]
Pulling PRs out of the freezer ... Brian, any chance that you could hunt down a reviewer for this PR?

**Comment by jrwest** [comment]
added to kill bill so maybe it has a better chance of getting a reviewer (maybe not?)

**Comment by jtuple** [comment]
Anytime to do this for 2.0 or should we punt to 2.1?

**Comment by reiddraper** [comment]
Is this blocked on something? Should we be moving to 2.1?

**Comment by bsparrow435** [comment]
Nope, just needs a review. I haven't touched it in a while. Will need a
rebase before merge.

**Comment by reiddraper** [comment]
This has languished for quite some time. I will be moving to 2.1 if I don't hear any objections before the end-of-day.

**Comment by reiddraper** [comment]
@bsparrow435 going once before moving to 2.1. That ok?

**Comment by reiddraper** [comment]
Moved to 2.1.

**Comment by yorkshire-steve** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
