### PR TITLE
When binary encoding timestamps, 24 bits is enough for secs, micros

### PR DESCRIPTION
**Pull request by russelldb**
Their maximum value is 999999.

Also, I bet we could get away with fewer bytes for Mega Seconds
(16 bytes gives us another 272 years, 24 gives us ~0.5million years)

### CODE REVIEW

**Comment by russelldb** [comment]
Actually, realised this bumps the version, not worth the trouble, is it?

**Comment by jrwest** [comment]
Yea I agree its probably a pain to bump the version for just this change but I think its a good thing to keep on a list for `v2`. Unfortunately, I missed this in v1 :(. Perhaps open an issue so we can keep track of it? Or leave the PR open for now?

**Comment by russelldb** [comment]
Added an issue to track this and other wishes for v2 binary format, @jrwest I reviewed the binary format, should have caught this then, but it is only ~2bytes, what's that between friends?

**Comment by jrwest** [comment]
ha, not so much between friends, but a bit between millions of friends ;)

**Pull request closed without merging**
