### PR TITLE
fix #929: wait for riak_kv_stat to unregister

### LINKED ISSUE #929: application already started pattern match bug
Since we turned on EQC for the builders, Riak KV has not been passing eunit. With `make test`, we get the following error:

```
module 'riak_kv_delete'
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
  undefined
  *** context setup failed ***
**in function riak_kv_test_util:'-do_dep_apps/2-fun-0-'/2 (src/riak_kv_test_util.erl, line 264)
in call from lists:foldl/3 (lists.erl, line 1248)
in call from riak_kv_test_util:setup/2 (src/riak_kv_test_util.erl, line 165)
**error:{badmatch,
    {error,
        {bad_return,
            {{riak_kv_app,start,[normal,[]]},
             {'EXIT',
                 {{case_clause,
                      {error,
                          {{already_started,<0.6340.3>},
                           {child,undefined,...}}}},
                  [{riak_core_stats_sup,start_server,1,[{file,...},{...}]},
                   {riak_core,register_mod,3,[{...}|...]},
                   {riak_core,register,2,[...]},
                   {riak_kv_app,start,2,...},
                   {application_master,start_it_old,...}]}}}}}}
```

Sometimes it fails on other modules too, like `riak_kv_pb_object`. You can [see the full logs](http://buildbot.bos1/builders/test-riak_kv/builds/1315/steps/shell_3/logs/stdio). I've only been able to reproduce this:
1. With EQC installed
2. With a full `make test`. Running individual suites does not show the bug.

I've tried [this patch](https://gist.github.com/reiddraper/4c23d8e67a49c1b0400c), but it just [changes the error](https://gist.github.com/reiddraper/62cb67b03b1c775e9117).

I've enlisted @vinoski to help me track this down as well.

### PR DESCRIPTION
**Pull request by vinoski**
The {{already_started, ...}, {child, ...}} error noted in the description
of issue #929 is caused by an instance of riak_kv_stat trying to register
its name when another instance is already registered. Add
riak_kv_test_util:wait_for_unregister/1 and use it in
riak_kv_test_util:cleanup/3 to wait for the registered instance of
riak_kv_stat to unregister and stop. Remove similar functionality in
test/get_put_monitor_eqc.erl and make that module call
riak_kv_test_util:wait_for_unregister/1 instead.

Also add goldrush to the app list in riak_kv_test_util:dep_apps/2 to ensure
it's started and stopped correctly; this prevents crash dumps caused by
{application_terminated,goldrush,killed} at the end of "make test".

### CODE REVIEW

**Comment by reiddraper** [comment]
@vinoski has gotten things much closer. Thanks. There seems to be one issue left before KV is green again:

```
Reason: {invariant,
       [{{riak_kv, node, puts, fsm, active}, {expected, 0},
         {actual, -1}}]}
*failed*
in function get_put_monitor_eqc:'-eqc_test_/0-fun-2-'/1 (test/get_put_monitor_eqc.erl, line 36)
**error:{assertEqual_failed,[{module,get_put_monitor_eqc},
                     {line,36},
                     {expression,"quickcheck ( eqc : testing_time ( 90 , ? QC_OUT ( prop ( ) ) ) )"},
                     {expected,true},
                     {value,false}]}
```

In case someone has any idea what this means from experience: @russelldb @engelsanchez @andrewjstone @engelsanchez.

---

Sidenote: I'm still seeing the `Erlang has closed` 'errors' as well. Not sure if they're harmless or not.

**Comment by reiddraper** [comment]
Oh, and the error I pasted above is from [the build output](http://buildbot.bos1/builders/test-riak_kv/builds/1323/steps/shell_3/logs/stdio).

**Comment by andrewjstone** [comment]
I'm seeing this error when running `make test` as well.

```
  riak_kv_pb_object:398: empty_bucket_key_test_ (RpbPutReq with empty key is disallowed)...*failed*
in function riak_kv_pb_object:'-request/3-fun-1-'/1 (src/riak_kv_pb_object.erl, line 426)
in call from riak_kv_pb_object:request/3 (src/riak_kv_pb_object.erl, line 426)
in call from riak_kv_pb_object:'-empty_bucket_key_test_/0-fun-1-'/0 (src/riak_kv_pb_object.erl, line 398)
**error:{assertMatch_failed,[{module,riak_kv_pb_object},
                     {line,426},
                     {expression,"Result"},
                     {pattern,"{ ok , _ }"},
                     {value,{error,closed}}]}
```

**Comment by andrewjstone** [comment]
get_put_monitor_eqc passed for me in `make test`. Only error was one above, which I think is unrelated.

**Comment by andrewjstone** [comment]
:+1:

**Comment by vinoski** [comment]
@andrewjstone: we see `get_put_monitor_eqc` fail every time on one of the slow fedora build machines even though it always passes elsewhere.

**Comment by vinoski** [comment]
@reiddraper should we create a new issue for the remaining `get_put_monitor_eqc` problem?

**Comment by vinoski** [comment]
Also seeing these two errors regularly, only under `make test`:

```
  riak_kv_eleveldb_backend: retry_test...*failed*
in function riak_kv_eleveldb_backend:retry_test/0 (src/riak_kv_eleveldb_backend.erl, line 960)
**throw:{unexpected,
    {timeout,#Ref<0.0.0.153341>,
        {'$gen_event',
            {riak_vnode_req_v1,undefined,ignore,
                {backend_callback,#Ref<0.0.0.153340>,merge_check}}}}}

  riak_kv_eleveldb_backend: retry_fail_test...*failed*
in function riak_kv_eleveldb_backend:retry_fail_test/0 (src/riak_kv_eleveldb_backend.erl, line 1017)
**throw:{expect_fail,running}
```

**Comment by vinoski** [comment]
See issues #936 and #937 for the other problems described in previous comments.

**Pull request merged**
