### PR TITLE
kv_vnode calling coverage_filter with 'all'

### PR DESCRIPTION
**Pull request by reiddraper**
In [this code](https://github.com/basho/riak_kv/blob/e66f3ffdc637d0e2385301f74d984c0632029493/src/riak_kv_vnode.erl#L766), kv_vnode calls riak_kv_coverage:build_filter with the atom `all` as the first argument. The type spec for this function expects a `binary()`. Digging through the call stack, I couldn't find any cases where we pattern match on an atom or specifically the atom `all`. Any ideas?

cc @kellymclaughlin, who I believe wrote this code.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
Yes, because the third parameter on that line you pointed out is `undefined` then only one of the first two guard expression of [this](https://github.com/basho/riak_kv/blob/e66f3ffdc637d0e2385301f74d984c0632029493/src/riak_kv_coverage_filter.erl#L60) `if` block will ever match in this case. So it's really just a junk parameter. You could change the spec or change the atom to be more clear. The best solution might be to add a `build_filter/2` function though this would require slightly more net changes than any other option.

**Comment by reiddraper** [comment]
Aha, perfect. I should be able to make a PR to fix this now. Thanks.

**Comment by reiddraper** [comment]
In [this particular call-site](https://github.com/basho/riak_kv/blob/e66f3ffdc637d0e2385301f74d984c0632029493/src/riak_kv_vnode.erl#L766), we could avoid even calling a function and simply use `ItemFilter`, or would that break too much of an abstraction?

**Comment by reiddraper** [comment]
Blah, ignore that comment. I missed the call to `build_item_filter`, which we _could_ just call directly, were it exported.

**Comment by reiddraper** [comment]
Just pushed cd46b2222f0db477f4c523a60588fa74e9c9ba99 to address this.

**Comment by kellymclaughlin** [comment]
+1 cd46b2222f0db477f4c523a60588fa74e9c9ba99

**Comment by reiddraper** [comment]
I'll retry this build once #937 is merged in, I think the tests should be green.

**Comment by reiddraper** [comment]
@borshop merge please

**Pull request merged**
