### PR TITLE
Expose FSM timeouts via the HTTP API

### PR DESCRIPTION
**Pull request by evanmcc**
adding the header 'X-Riak-Timeout=<some_int_in_ms>' will now cause the request to return a timeout error if it takes longer than the specified time interval.  This works for DELETEs, PUTs, and GETs, but in the case of a PUT or a get, a timeout failure does not guarantee anything about the state of the cluster when it happens.  The PUT or DELETE may or may not have succeeded; the correct course of action after the timeout is to retry the same action until a 200 is received.

### CODE REVIEW

**Comment by evanmcc** [comment]
The associated riak_test is here:  https://github.com/basho/riak_test/pull/150

**Comment by seancribbs** [comment]
Too late for 1.3, but I like the general idea.

**Comment by evanmcc** [comment]
Couldn't make heads or tails of the travis output.

**Comment by seancribbs** [comment]
@evanmcc Not to delay this PR, but we should also add these to the appropriate PB messages.

**Comment by evanmcc** [comment]
Yup; it's been on my todo list since I submitted the first one, but it's a
bit more involved, so I am only halfway done.

As a related question: is the riak erlang client easily available in
riak_test?

**Comment by chardan** [comment]
+1

**Comment by seancribbs** [comment]
@evanmcc Yes, `rt:pbc(Node)` will grant you a new client.

**Pull request merged**
