### PR TITLE
Fix/az/assorted dialyzer issues

### PR DESCRIPTION
**Pull request by hmmr**
This is continuation of #1164.

### CODE REVIEW

**Comment by hmmr** [comment]
Cherry-picked, squashed, inserted into https://github.com/basho/riak_kv/pull/1268. It is not against standard riak, though. Once that PR is in, the cumulative commit can replace this series.

**Comment by andytill** [comment]
Can this PR be closed now that the dialyzer fixes have been merged?

**Comment by hmmr** [comment]
In fact, these dialyzer errors have all been dealt with in other PRs.

**Comment by andytill** [comment]
Many thanks to @puzza007 for these fixes!

**Pull request closed without merging**
