### PR TITLE
use exometer metrics

### PR DESCRIPTION
**Pull request by uwiger**
This is a new pull request for the Exometer adaptation, with a cleaner commit history (all changes collected into one diff).

See riak [PR #576](https://github.com/basho/riak/pull/576)

The old riak_kv PR was #748 (for comment history)

### CODE REVIEW

**Comment by jburwell** [comment]
The acceptance test check list for this PR is as follows:

### Testing
- [ ] manual verification of code
- [ ] eunit     (w/ gist of output) 
- [ ] EQC       (w/ gist of output) 
- [ ] riak_test (w/ gist of output) 
- [ ] Dialyzer
- [ ] XRef
- [ ] Coverage reports

### Documentation
- [ ] internal docs (design docs)
- [ ] external docs (docs.basho.com)
- [ ] man pages

**Comment by reiddraper** [comment]
@jburwell, FYI, of the things mentioned (eunit, dialyzer, xref) will be run as part of bors/buildbot, and their stdio will be part of that run.

**Comment by jburwell** [comment]
@reid I am aware that the check is automated.  However, the PRs are failing these checks now.  Therefore, works needs to be done so that the PRs will pass the bors checks on promotion.

**Comment by seancribbs** [comment]
There are config mappings changed here, so they should also be reviewed by PMs and CSEs. The one I see is likely not necessary (or useful) to end-users.

**Comment by jburwell** [comment]
Superseded by https://github.com/basho/riak_kv/pull/1044

**Pull request closed without merging**
