### PR TITLE
Enable bloom filters for AAE LevelDB instances

### PR DESCRIPTION
**Pull request by jtuple**
This pull-request ensures that the LevelDB instances used by AAE take advantage of bloom filters. AAE was designed assuming bloom filters were enabled, and not enabling them was an oversight. This should help AAE tree rebuild times in certain scenarios.

Sibling PR: Added harness for AAE rebuild benchmarking in basho/riak_test#488

For 100k keys, single node, N=3 running benchmark against Riak w/ and w/o this PR shows:

```
Average build time: 19721090 us (w/o bloom filter)
Average build time: 19020692 us (w/ bloom filter)
```

Granted, those results are likely in the noise. But, at least shows that things aren't worse. Currently running some larger benchmark, and will add results to this pull request before merging.

### CODE REVIEW

**Comment by jonmeredith** [comment]
+1 merge

Before change, anti_entropy/*/LOG files contain

```
2013/12/19-12:36:12.648069 1151b5000          Options.filter_policy: NULL
```

After

```
2013/12/19-12:34:20.197864 112fbc000          Options.filter_policy: leveldb.BuiltinBloomFilter2
```

**Comment by jrwest** [comment]
Just a note we should make the same change in `riak_core` for 2.0. I had a note to do so....somewhere....

**Comment by jaredmorrow** [comment]
@jrwest already done in https://github.com/basho/riak_core/pull/483

**Comment by jtuple** [comment]
FYI, here's the results from running the benchmark w/ 1 million keys, N=3, single node, ring size=4 cluster:

with bloom filter enabled:

```
11:01:41.279 [info] Enable AAE and run tree build experiment
11:01:41.280 [info] Wait until AAE builds all partition trees across ['dev1@127.0.0.1']
11:04:25.464 [info] Build took 164184075 us
11:04:26.971 [info] Wait until AAE builds all partition trees across ['dev1@127.0.0.1']
11:07:01.140 [info] Build took 154168436 us
11:07:02.643 [info] Wait until AAE builds all partition trees across ['dev1@127.0.0.1']
11:10:02.838 [info] Build took 180194904 us
11:10:04.355 [info] Wait until AAE builds all partition trees across ['dev1@127.0.0.1']
11:12:48.538 [info] Build took 164183327 us
11:12:50.040 [info] Wait until AAE builds all partition trees across ['dev1@127.0.0.1']
11:15:50.244 [info] Build took 180203178 us
11:15:50.244 [info] Average build time: 210733480 us
```

without bloom filter:

```
11:28:56.704 [info] Enable AAE and run tree build experiment
11:28:56.705 [info] Wait until AAE builds all partition trees across ['dev1@127.0.0.1']
11:31:56.903 [info] Build took 180198860 us
11:31:58.423 [info] Wait until AAE builds all partition trees across ['dev1@127.0.0.1']
11:34:58.625 [info] Build took 180201392 us
11:35:00.145 [info] Wait until AAE builds all partition trees across ['dev1@127.0.0.1']
11:38:00.348 [info] Build took 180202948 us
11:38:01.861 [info] Wait until AAE builds all partition trees across ['dev1@127.0.0.1']
11:41:02.065 [info] Build took 180203556 us
11:41:03.574 [info] Wait until AAE builds all partition trees across ['dev1@127.0.0.1']
11:44:03.771 [info] Build took 180196330 us
11:44:03.771 [info] Average build time: 225250771 us
```

About 6% slower w/o bloom when looking at average build time. Probably still within the noise. But, who knows. Since I'm testing on an SSD, the w/o bloom issue is less pronounced. So, this change likely has even more benefit on very busy clusters running spinning disks.

**Pull request merged**
