### PR TITLE
Specified return code for riak_kv_console:bucket_type_status

### LINKED ISSUE #930: incorrect return code for riak-admin bucket-type status
riak-admin bucket-type status <created bucket> ( successful ) returns a non-zero (failure) exit code, and the same command on a non-existent bucket returns a zero exit code.

riak_kv_console:bucket_type_status/1 actually returns [ok,ok,ok... ] on success, which gets treated like an error in nodetool, thus a halt(1). Undefined is caught and 'ok' is returned, thus the zero exit code from riak-admin.

'ok' should be returned if the bucket-type is found, and {error, SomethingUseful} could be returned if it's not to assist command line tools/scripts in automating the creation of bucket types.

### PR DESCRIPTION
**Pull request by glickbot**
This commit fixes #930

### CODE REVIEW

**Comment by jrwest** [comment]
+1 a85edb4

**Comment by reiddraper** [comment]
FYI, there are still some eunit tests failing that @vinoski and I are working on. This is happening on develop too.

**Comment by reiddraper** [comment]
Put into 2.0-RC milestone (along with #930), and am retrying the build.

**Comment by reiddraper** [comment]
@borshop merge

**Pull request merged**
