### PR TITLE
Add metadata cache

### PR DESCRIPTION
**Pull request by evanmcc**
NB: this patch has merged https://github.com/basho/riak_kv/pull/695 and should not be merged until after that patch has landed (and rebased if that patch changes).

This change adds an ETS table per vnode to act as a cache for the vclocks and index specs of any values that have recently been gotten or put.  This is meant to save round-trips to the disk in common get-then-put workflows on slower disks.

The cache is size limited, and setting the size to 0 will disable it, since it is a slight performance hit in certain situations (e.g. using the memory backend, when all of your data fits into RAM, etc).

### CODE REVIEW

**Comment by evanmcc** [comment]
You can also use the view at this link for a cleaner diff:

https://github.com/basho/riak_kv/compare/jd-cuttlefish...feature/pevm-metadata-cache

**Comment by slfritchie** [comment]
It probably wouldn't hurt to add a capability to the memory backend to allow it to say "please, don't cache me, I'm fast, honest".  The only problem is choosing the name for the capability.....

**Comment by jrwest** [comment]
just pinging this PR since #695 has been updated (and will probably merged shortly)

**Comment by slfritchie** [comment]
Evan, sorry, I've run out of review time this week.  Ping me again if you can't find a reviewer, and I'll return here.

**Comment by evanmcc** [comment]
Thanks, Scott.  We'll get it reviewed, no problem.  I'll add the cap that
you suggested for the memory backend and yessir.

**Comment by slfritchie** [comment]
Is this a post-2.0 item?

**Comment by evanmcc** [comment]
it was supposed to be a 2.0 item?  I think that it could be
helpful/worthwhile, but we're running out of time/review bandwidth.  In
terms of perf improvements if we have to triage my reviews I think that
this is #2 after the review for the FSM refactor.

**Comment by jtuple** [comment]
FYI, I'm reviewing based on the `feature/pevm-metadata-cache.merged` branch I created by merging this branch to develop + fixing merge conflicts. See the newer diff [here](https://github.com/basho/riak_kv/compare/develop...feature;pevm-metadata-cache.merged)

We should either force push that branch on top of this one.  Or, if you prefer rebasing, rebase `feature/pevm-metadata-cache` on top of `develop`, resolving conflicts the same as I did in the merged branch.

**Comment by evanmcc** [comment]
new diff looks reasonable at first glance, I am OK w/ force-pushing

On Mon, Dec 23, 2013 at 12:53 PM, Joseph Blomstedt <notifications@github.com

**Comment by evanmcc** [comment]
closing in favor of https://github.com/basho/riak_kv/pull/781

**Pull request closed without merging**
