### PR TITLE
Clean up get/put FSM start code and remove non-sidejob code paths

### PR DESCRIPTION
**Pull request by nickelization**
This PR removes a bunch of code that allowed us to run riak_kv with sidejob disabled. None of our customers run with overload protection disabled, and now that sidejob has been pretty thoroughly vetted in production, we no longer need an escape hatch. Removing the non-sidejob code (as well as associated test code) will cut down on risk and maintenance costs. Performance should also be improved a little bit since we avoid having to do the extra check for sidejob vs non-sidejob when starting a get/put FSM.

These changes also remove the obsolete riak_kv_get_fsm and riak_kv_put_fsm supervisors, and renames the get/put FSM start_link functions to "start", since they don't actually link to the calling process. (Although the start_link function name is kept as an alias to avoid any potential problems during rolling upgrades.)

### CODE REVIEW

**Comment by nickelization** [comment]
Also see basho/riak_kv#1178 (RIAK-2157) (RIAK-2567) for more background. We'll also have to update repl to not use the get FSM supervisor, and instead just start a get FSM directly, but that'll be a nice easy one-line fix.

**Comment by jadeallenx** [comment]
Nice work

**Comment by nickelization** [comment]
Thanks!

**Comment by ian-mi** [comment]
Looks good to me. I'm glad you cleaned up the naming; start_link is currently a lie. I also approve of tearing out the get / put monitor code.

This might be a good opportunity to examine the riak_client behaviour as well. It seems unnecessary to use proc_lib:spawn_link to call the fsm start function rather than making a synchronous call. Perhaps the reason for this is outdated?

**Comment by nickelization** [comment]
@ian-mi Thanks! Yeah, I'm not sure about the riak_client code, that's a good point. I'd like to look into that but I think due to time constraints I probably won't get to it until after 2.2 is out. I'll put it on my TODO list though for sure.

If all the changes look good, could I get a +1 so I can go ahead and merge this? Once this is merged I'll also go into riak_repl and add a PR to switch it over to use the new API instead of starting things under the now-defunct FSM supervisor.

**Comment by ian-mi** [comment]
Sounds good.

+1 3cea5ae

**Comment by bsparrow435** [comment]
+1 3cea5ae202e9bdda72bab4cb0649c2c7265869ad

**Comment by nickelization** [comment]
@borshop merge

**Pull request merged**
