### PR TITLE
Ensure nodes don't transition to exiting too soon

### PR DESCRIPTION
**Pull request by andrewjstone**
Add ready_to_exit/0 callback to riak_kv_vnode and
riak_kv_ensembles:local_ensembles/0 to ensure that nodes don't
transition from leaving to exiting while they still have ensemble peers
in use.

### CODE REVIEW

**Comment by andrewjstone** [comment]
Part of fix for basho/riak_core#572

**Comment by reiddraper** [comment]
@andrewjstone what milestone should this issue be under?

**Comment by andrewjstone** [comment]
2.0 RC. Just added.

**Comment by slfritchie** [comment]
Looks good, +1, thanks!

**Comment by jtuple** [comment]
+1

Individual pull-request looks good. This is part of a larger set of pull-requests. Entire set of changes was reviewed/tested as part of basho/riak_test#593

FYI, we'll need to push out a final commit to fix up the line number changes for `dialyzer.ignored-warnings` to make this bors clean. But, need to wait for the dependent `riak_ensemble` and `riak_core` changes to merge in first anyway.

Looks like I forgot to assign myself to this pull-request when I started the review weeks back (before getting distracted on other things). Finally got back to this and finished up today. In any case, thanks for the extra pair of eyes @slfritchie

**Comment by andrewjstone** [comment]
:+1: ffc11cb

**Comment by andrewjstone** [comment]
:+1: 17360b6

**Comment by jtuple** [comment]
@borshop merge

**Pull request merged**
