### PR TITLE
Make `dvv_enabled` a bucket property

### PR DESCRIPTION
**Pull request by russelldb**
Set it's default to `false` on legacy/default buckets
Set it's default to `true` on typed buckets

Update all the tests and associated places this change touches

### CODE REVIEW

**Comment by russelldb** [comment]
Last one for @cmeiklejohn , I pwomise.

**Comment by cmeiklejohn** [comment]
@rdb Isn't this the one I was supposed to test?  You referenced it in #889.

**Comment by russelldb** [comment]
Re-opened as https://github.com/basho/riak_kv/pull/891 pointing at `develop` rather that the optimisations branch.

**Comment by cmeiklejohn** [comment]
OK.

**Pull request closed without merging**
