### PR TITLE
Comment out get_put_monitor_eqc property

### PR DESCRIPTION
**Pull request by kellymclaughlin**
The `get_put_monitor_eqc` property exhibits nondeterministic failure on certain machines and is preventing unrelated work from being merged. Comment out the test temporarily until the failure can be resolved or the test can be replaced.
#944 is open as a reminder to investigate and reinstate the test before 2.0

### CODE REVIEW

**Comment by reiddraper** [comment]
Yeah, smart idea. We still have a sigsegv that occasionally plagues us, but it hasn't been hitting often yet.

**Comment by kellymclaughlin** [comment]
@borshop merge

**Comment by kellymclaughlin** [comment]
@borshop: retry

**Comment by reiddraper** [comment]
Ugh, just what I feared:

```
  riak_kv_eleveldb_backend:1045: eqc_test_...process killed by signal 11
program finished with exit code -1
elapsedTime=413.986523
```

This is the leveldb/eleveldb @vinoski has been tracking down.

@kellymclaughlin FYI, telling borshop to retry only works on the commit comments, at the moment.

**Pull request merged**
