### PR TITLE
fix #936: handle slow metrics for get_put_monitor_eqc

### LINKED ISSUE #936: get_put_monitor_eqc test failure
On a slow smp:2:2 Fedora buildbot box, the `get_put_monitor_eqc` test fails reliably with this error:

```
Reason: {invariant,
       [{{riak_kv, node, puts, fsm, active}, {expected, 0},
         {actual, -1}}]}
*failed*
in function get_put_monitor_eqc:'-eqc_test_/0-fun-2-'/1 (test/get_put_monitor_eqc.erl, line 36)
**error:{assertEqual_failed,[{module,get_put_monitor_eqc},
                     {line,36},
                     {expression,"quickcheck ( eqc : testing_time ( 90 , ? QC_OUT ( prop ( ) ) ) )"},
                     {expected,true},
                     {value,false}]}
```

### PR DESCRIPTION
**Pull request by vinoski**
On slow systems the get_put_monitor_eqc test could fail due to not waiting
long enough for folsom metrics updates. Add bounded wait for metrics to
become non-negative before checking them against expected results. Also
increase max test time from 120 to 150 to avoid test timeout on slow
systems.

### CODE REVIEW

**Comment by andrewjstone** [comment]
Yay! Nice work @vinoski 
Still not sure why folsom would ever have values below 0 for counters, but I'm a rational person mostly, so maybe that's it.

**Comment by andrewjstone** [comment]
+1  ca0dc39

**Comment by vinoski** [comment]
@andrewjstone it appeared that a series of increments and decrements of the metrics had just not finished by the time the tests sampled them for comparison against expected values, and the symptom was always that the metrics had negative values when failing. My change just checks the metrics for negative values before comparing them, giving them a little more time to settle and reach their ultimate values first.

**Comment by seancribbs** [comment]
@vinoski In the future, it's best to say "@borshop merge"

**Comment by vinoski** [comment]
good to know, thanks @seancribbs

**Pull request merged**
