### PR TITLE
Some small dialyzer progress

### PR DESCRIPTION
**Pull request by reiddraper**
There are still tons of dialyzer errors not fixed by this PR, but I figured it was better to merge things early, particularly since the commits are not related to each-other. I'll add some comments if I think there are commits that need extra review by the original author.

### CODE REVIEW

**Comment by reiddraper** [comment]
Blah, made a mistake in a commit. I'll be force-pushing here shortly.

**Comment by seancribbs** [comment]
@reiddraper where possible could you also include the warnings fixed by each commit? @cmeiklejohn and I started doing that so it's more clear.

**Comment by reiddraper** [comment]
> @reiddraper where possible could you also include the warnings fixed by each commit? @cmeiklejohn and I started doing that so it's more clear.

Sure. Do you want me to go back and amend the commits? Or just going forward?

**Comment by reiddraper** [comment]
I think if/once this is merged, I'll file separate issues for dialyzer work on the remaining modules, which, at first glance, required more domain expertise.

**Comment by cmeiklejohn** [comment]
Just going forward is fine.  I'll take the review of this now.

**Comment by cmeiklejohn** [comment]
Left some comments, :+1: otherwise.

**Comment by reiddraper** [comment]
@cmeiklejohn have all of the review comments been handled? If so, ready to merge?

**Comment by cmeiklejohn** [comment]
Merge away.

**Pull request merged**
