### PR TITLE
Companion commit of changes to tests arising from the renaming of

### PR DESCRIPTION
**Pull request by gordonguthrie**
integer -> sint64
float -> double

and consistent handling of the name varchar

Also includes a bug fix for the query compiler blowing up
with a key in the proper order (ie the quantum last)

### CODE REVIEW

**Comment by gordonguthrie** [comment]
Goes with these PRs
https://github.com/basho/riak_ql/pull/36
https://github.com/basho/eleveldb/pull/167
https://github.com/basho/riak_test/pull/915

**Comment by alexmoore** [comment]
Works with the addition of https://github.com/basho/riak_pb/pull/153.

**Comment by alexmoore** [comment]
Client tests work with all the companion PRs, getting a few errors when running `make test`. 

```
sql_compilation_end_to_end:plain_qry_test
sql_compilation_end_to_end:spanning_qry_test
riak_kv_qry_compiler:simple_filter_typing_test
riak_kv_qry_compiler:simple_rewrite_test
riak_kv_qry_compiler:simple_rewrite_test
riak_kv_qry_compiler:simplest_test
riak_kv_qry_compiler:simple_with_filter_1_test
riak_kv_qry_compiler:simple_with_filter_2_test
riak_kv_qry_compiler:simple_with_filter_3_test  
riak_kv_qry_compiler:simple_with_2_field_filter_test
riak_kv_qry_compiler:complex_with_4_field_filter_test
riak_kv_qry_compiler:complex_with_boolean_rewrite_filter_test
riak_kv_qry_compiler:simple_spanning_boundary_test
```

**Comment by DSomogyi** [comment]
RTS-510

**Comment by andytill** [comment]
All the tests are passing now when I have the branches in alignment.  There are just way too many tests for riak_ql in riak_kv, we should move them out, a lot are probably duplicated in riak_kv anyway.

**Comment by hazen** [comment]
@andytill Agreed. I noticed that yesterday when updating the DDL tests inside KV.  My thought was, why are these here?

**Comment by hazen** [comment]
I think this has been duplicated by https://github.com/basho/riak_kv/pull/1253 https://bashoeng.atlassian.net/browse/RTS-523

**Comment by andytill** [comment]
@borshop retry

**Comment by andytill** [comment]
@borshop: retry 68a0df0

**Comment by hazen** [comment]
Mostly this is a duplicate of https://github.com/basho/riak_kv/pull/1253. There are a couple type changes which still need to be done, but will be covered in another PR.

**Pull request closed without merging**
