### PR TITLE
Change application:get_env/2 -> app_helper:get_env

### PR DESCRIPTION
**Pull request by slfritchie**
If the key is found, `application:get_env/2` returns an {ok, Value}`wrapper which is *not* stripped off elsewhere in this module.  The`app_helper:get_env/2` function will strip it off, as we need.

### CODE REVIEW

**Comment by jonmeredith** [comment]
+1 52a8a25626cd5f59074771ab8c77374e0bc4d6b5

Works for me.  Did a quick audit and the other dtrace hooks do not use the fsm_trace_enabled stuff.

```
(riak@127.0.0.1)36> application:unset_env(riak_kv, fsm_trace_enabled). 
ok
(riak@127.0.0.1)37> redbug:start(riak_core_dtrace).                    
{1892,11}
(riak@127.0.0.1)38> C:put(riak_object:new(<<"b">>,<<"k">>,<<"v">>)).   
ok
redbug done, timeout - 0                                                    
(riak@127.0.0.1)39> application:set_env(riak_kv, fsm_trace_enabled, true).  
ok
(riak@127.0.0.1)40> redbug:start(riak_core_dtrace).                       
{1894,11}
(riak@127.0.0.1)41> C:put(riak_object:new(<<"b">>,<<"k">>,<<"v">>)).      

07:12:13 <0.12966.0>({riak_kv_put_fsm,init,1}) {riak_core_dtrace,put_tag,
                                                [[<<"b">>,44,<<"k">>]]}

07:12:13 <0.12966.0>({riak_kv_put_fsm,init,1}) {riak_core_dtrace,enabled,[]}

07:12:13 <0.12966.0>({riak_kv_put_fsm,init,1}) {riak_core_dtrace,dtrace,
                                                [enabled_check]}

07:12:13 <0.12966.0>({riak_kv_put_fsm,init,1}) {riak_core_dtrace,dtrace,
                                                [520,[0],["init",<<>>]]}

07:12:13 <0.12966.0>({riak_kv_put_fsm,init,1}) {riak_core_dtrace,dtrace,
                                                [521,
                                                 [0],
                                                 ["prepare",
                                                  "riak@127.0.0.1"]]}

07:12:13 <0.12966.0>({riak_kv_put_fsm,init,1}) {riak_core_dtrace,dtrace,
                                                [522,[3,2,0,2],[]]}

07:12:13 <0.12966.0>({riak_kv_put_fsm,init,1}) {riak_core_dtrace,dtrace,
                                                [523,[0],[]]}
ok

07:12:13 <0.12966.0>({riak_kv_put_fsm,init,1}) {riak_core_dtrace,dtrace,
                                                [524,[],["riak@127.0.0.1"]]}

07:12:13 <0.12966.0>({riak_kv_put_fsm,init,1}) {riak_core_dtrace,dtrace,
                                                [525,
                                                 [1],
                                                 ["639406966332270026714112114313373821099470487552"]]}

07:12:13 <0.12966.0>({riak_kv_put_fsm,init,1}) {riak_core_dtrace,dtrace,
                                                [525,
                                                 [2],
                                                 ["639406966332270026714112114313373821099470487552"]]}
redbug done, msg_count - 10
```

**Comment by jonmeredith** [comment]
Merge at will @slfritchie

**Comment by seancribbs** [comment]
@borshop merge

@jonmeredith ^^

**Comment by jonmeredith** [comment]
I know, I was giving Scott the pleasure, but I guess it's not as much fun to ask the bot to do it :)

**Pull request merged**
