### PR TITLE
Cuttlefish schema for background manager subsystem (aae and handoff) kill/enable switch

### PR DESCRIPTION
**Pull request by buddhisthead**
Add cuttlefish schema for the KV's background manager "use/kill/enable" switch. When set to "false", KV won't use the background manager for the specified subsystems, namely AAE tree rebuilding and Handoff.
- On by default
- Advanced mode setting means it doesn't get generated into the config file "riak.config"
- Look for it in "dev/devN/data/generated.configs" where N=1..6 after `make devrel`

I examined the `generated.configs` file to confirm it was present and had the correct default value… you should see this:

```
...
 {riak_kv,
     [{aae_use_background_manager,true},
      {handoff_use_background_manager,true},
      {max_siblings,100},
     …
```

### CODE REVIEW

**Comment by seancribbs** [comment]
- [x] CSE approval
- [x] PM approval
- [x] Eng testing

**Comment by gburd** [comment]
+1

**Comment by joedevivo** [comment]
+1

Some tests fail on my machine, but nothing to do with the schema tests.

**Comment by seancribbs** [comment]
@jmshoffs0812 @angrycub @mk1s Need a +1 from a CSE

**Comment by angrycub** [comment]
+1

**Comment by seancribbs** [comment]
Oops, doesn't merge cleanly anymore. Will rebase.

**Comment by joedevivo** [comment]
Echo my previous comment: "Some tests fail on my machine, but nothing to do with the schema tests."

**Comment by joedevivo** [comment]
Would love to see the tests passing, since they pass on develop

**Comment by reiddraper** [comment]
@borshop merge

**Pull request merged**
