### PR TITLE
Merge/2.1 to develop 2015.10.29

### PR DESCRIPTION
**Pull request by fadushin**
This is a clean merge (no conflicts) from the 2.1 branch to develop, pulling in the changes that have gotten merged to 2.1 from 2.0, as well as any new fixes in 2.1.

### CODE REVIEW

**Comment by JeetKunDoug** [comment]
+3?

**Comment by JeetKunDoug** [comment]
:+1: f3ef698

**Comment by jonmeredith** [comment]
+1

**Comment by fadushin** [comment]
@borshop merge

**Pull request merged**
