### PR TITLE
Changes to riak_client so that if legacy_keylisting is not specified in the config, the legacy code will be used.

### PR DESCRIPTION
**Pull request by kellymclaughlin**

### CODE REVIEW

**Comment by Vagabond** [comment]
Why not default the value in the env section of the riak_kv.app file?

**Comment by seancribbs** [comment]
@Vagabond Because you want new clusters to use the new setting?

**Comment by Vagabond** [comment]
But it'll be in the app.config file defaulted to false for new clusters, the app.config file overides the app.src file.

**Comment by kellymclaughlin** [comment]
Updated per your suggestion.

**Comment by Vagabond** [comment]
For absolute safety, the second clause of the case where you test for legacy_keylisting should probably be _, not false.

**Comment by kellymclaughlin** [comment]
Good point.

**Comment by Vagabond** [comment]
+1

**Pull request closed without merging**
