### PR TITLE
Backport put fsm forwarding.

### PR DESCRIPTION
**Pull request by lordnull**
Takes #627, #700, and #913 and puts them in one pull request to take the put fsm forwarding feature from 2.0 and place it in 1.4.

Tasks remaining:
- [ ] Create an r_t to test the feature. If that cannot be done in the next 3 days (EOD Friday) at least be able to create a step-by-step manual verification process.
- [ ] If commit c927c7faa8b (or its descendants) is correct & is well-reviewed, then it should also be applied to `develop`.

### CODE REVIEW

**Comment by slfritchie** [comment]
Sorry, -1, this patch set as-is doesn't work the way it does on `develop`.
1. Create a 5 node cluster with `vm.args` containing `+zdbbl 4`.
2. Suspend nodes 2 & 3, e.g. `kill -STOP $pid`.  Stopping them won't work.
3. Run the following Erlang code or equivalent on node1:
   
   {ok, C} = riak:local_client().  
   Big = list_to_binary(lists:duplicate(1024*1024, $x)).
   [begin timer:sleep(1000), spawn(fun() -> [{foo, Nd} ! Big || Nd <- nodes()] end), timer:sleep(100), Y = C:put(riak_object:new(<<"b">>, <<X:32>>, <<"val!">>)), io:format("Y was ~p at ~p\n", [Y, time()]) end || X <- lists:seq(0,10)].

Each put should be returning `ok` in less than 10 seconds.  Any delay beyond 10 seconds or any other return value is an error.  I see zero errors when using this procedure on `develop` but am seeing errors on this branch.

```
Y was ok at {18,30,4}
Y was ok at {18,30,5}
Y was ok at {18,30,6}
Y was {error,timeout} at {18,31,7}
Y was ok at {18,31,8}
[....]
```

**Comment by slfritchie** [comment]
I found the same behavior in `develop` ... I just had to work harder at it.

**Comment by jonmeredith** [comment]
Does that mean you've found an issue with put-foward-ackery?

On Thu, Aug 7, 2014 at 6:57 AM, Scott Lystig Fritchie <
notifications@github.com> wrote:

> I found the same behavior in develop ... I just had to work harder at it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/basho/riak_kv/pull/1009#issuecomment-51467339.

## 

Jon Meredith
VP, Engineering
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by slfritchie** [comment]
I've edited/updated my put loop recipe from 4 hours ago.

@jonmeredith Nope, it was a problem after the ackery.  See newly-pushed commit c927c7faa8b.

**Comment by lordnull** [comment]
I've been able to test this patch manually using some information from the client that requested this patch set, and it does address the specific problem. Developing an r_t solution proved problematic as the test case we had used sysrq, which is not exactly portable (nor safe for a test considering it reset the machine). However, using the info @slfritchie has pointed out (use of kill -STOP and kill -CONT), an r_t solution seems entirely possible.

**Comment by slfritchie** [comment]
Ping: comments on commit c927c7f?

**Comment by jonmeredith** [comment]
@lordnull ping - would like to give customer an update by end of their day (which is soon as they're on BST)

**Comment by lordnull** [comment]
r_t is not able to replicate exactly, but I was able to create a script with some notes on its use for a manual verification that this patch does solve the problem they described. I uploaded that script and notes to the ticket they opened.

**Pull request merged**
