### PR TITLE
Use the embedded counter inside the map

### PR DESCRIPTION
**Pull request by russelldb**
See https://github.com/basho/riak_dt/pull/93 for more details.

This PR also solves a couple of dialyzer issues, if you use this https://github.com/basho/riak_pb/pull/91 branch/PR of PB

See also https://github.com/basho/riak_test/pull/611

### CODE REVIEW

**Comment by reiddraper** [comment]
Once basho/riak_pb#91 is merged, I'll review and +1 the SHA for bors to build.

**Comment by seancribbs** [comment]
Mentioned on basho/riak_dt#93 -- be sure to remove the `add` operation from the API, since it was removed from `riak_dt_map`.

**Comment by seancribbs** [comment]
@reiddraper The dependent PR in riak_dt has not yet merged.

**Comment by reiddraper** [comment]
Ok, can wait for that too then.

**Comment by russelldb** [comment]
OK. I'm done with this. When https://github.com/basho/riak_dt/pull/93 finally merges (and https://github.com/basho/riak_pb/pull/93) this is ready (if you think it's ready, needs another look maybe @reiddraper / @seancribbs)

Hey look at that both the dt and pb pulls are 93. Very coincidence.

**Comment by seancribbs** [comment]
:+1: ab7ab81

**Comment by seancribbs** [comment]
@reiddraper Looks like pinning the riak_pb dep has prevented this from building properly. I am working on dialyzer fixes for riak_pb which should also help, then we should do the tag and bump dance.

**Comment by reiddraper** [comment]
sounds good

**Comment by seancribbs** [comment]
@borshop: retry

**Comment by seancribbs** [comment]
:+1: f6cb6cb

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
