### PR TITLE
use yokozuna or riak_search for {search, ...} MR inputs

### PR DESCRIPTION
**Pull request by beerriot**
_Note_: this should probably be considered non-merge-able until bucket-types land, since that has the potential for significant conflict, and redefinition of bucket-index mapping for yokozuna. I'm opening the PR now for comment and backup purposes.

There are two ways to use riak_search inputs for MapReduce:
- specify a {modfun, ...} input ({"module":...,"function":...} in json)
- specify a {search, ...} input ({"bucket":...,"query":...} in json)

This patch allows yokozuna to power the second type instead of
riak_search. The value of the "bucket" field is used as the name of the
yokozuna index.

This patch does not convert the modfun version, to keep from surprising
users, and to allow an escape hatch for people that need to use both.

If only one of riak_search or yokozuna is enabled, that system is chosen
to power search MR inputs.

If both are enabled, then the riak_kv's appenv 'mapred_search' must also
be defined as either 'riak_search' or 'yokozuna'. If it is not defined,
or it is defined as something else, and error will be returned from the MR.

If neither is enabled, an error is returned from the MR.

The automatic nature of the switch is intended to keep configuration as
minimal as possible: the extra riak_kv setting is only needed if _both_
riak_search and yokozuna are to be used, _and_ the user wants to use the
non-modfun forms. If only one search system is enabled, or only modfun
input forms are used, the correct thing just happens.

A test for this behavior is defined by `mapred_search_switch` in basho/riak_test#373.

### CODE REVIEW

**Comment by beerriot** [comment]
After discussion today, this PR should be amended to have yokozuna mode expect "index" instead of bucket in the input spec.

**Comment by seancribbs** [comment]
Not sure it was decided: does it make sense to allow the old "bucket" inputs, and have it imply "use the bucket's index, plus filter the 'bucket' field"?

**Comment by beerriot** [comment]
@seancribbs We can definitely allow the old "bucket" input and look up the index to use from that. We'll have to be careful about filtering the results that produces, though, since it might behave strangely if sorting and limiting are in play.

**Comment by seancribbs** [comment]
@beerriot Sure, that makes sense. I was thinking of the filter as part of the YZ query, but like Donnie I'm out of my element.

**Comment by beerriot** [comment]
Closing in favor of #664, which takes into account the discussion above.

**Pull request closed without merging**
