### PR TITLE
Add riak_kv_ensemble_backend:handle_down/4

### PR DESCRIPTION
**Pull request by andrewjstone**
Have the backend monitor the vnode and vnode proxy. The peer will
receive 'DOWN' messages and call riak_kv_ensemble_backend:handle_down/4
as a result.

Part of a fix for basho/riak_kv#985

### CODE REVIEW

**Comment by andrewjstone** [comment]
This probably warrants a test

**Comment by andrewjstone** [comment]
Test is here: https://github.com/basho/riak_test/pull/645
Test requires this PR as well: https://github.com/basho/riak_ensemble/pull/33

**Comment by lordnull** [comment]
:+1:  d92ee49

Test fails w/o this, passes with. code is straight forward.

**Comment by andrewjstone** [comment]
@borshop merge

**Pull request merged**
