### PR TITLE
Coerce the datatype property into an atom.

### PR DESCRIPTION
**Pull request by seancribbs**
When creating a bucket-type from the command-line, the `datatype`
property might not be an atom, so we should try to convert it to one
before passing it to the CRDT code.

### CODE REVIEW

**Comment by jrwest** [comment]
shouldn't the datatype coercion be handled in [`erlify_bucket_props`](https://github.com/basho/riak_kv/blob/develop/src/riak_kv_wm_utils.erl#L343)? This is used by both wm and the command line bucket type stuff.

**Comment by seancribbs** [comment]
@jrwest Addressed in d5b2326

**Comment by jrwest** [comment]
+1. didn't actually run the code that uses the datatype property, but the change is straightforward enough

**Comment by seancribbs** [comment]
Thanks! /cc @broach

**Pull request merged**
