### PR TITLE
Clean up QL/KV interface: no longer pass KV records in either direction.

### PR DESCRIPTION
**Pull request by macintux**
See basho/riak_ql#103

### CODE REVIEW

**Comment by macintux** [comment]
Build is failing because it's building against non-branched QL.

**Comment by hazen** [comment]
riak_tests look good except for `ts_cluster_create_table_via_sql`:

```
[{riak_kv_pb_timeseries,
 process,
 [function_clause,
{state,undefined,
 undefined,
 undefined}],
 [{file,
 \"src/riak_kv_pb_timeseries.erl\"},
{line,151}]},
{riak_api_pb_server,
 process_message,4,
 [{file,
 \"src/riak_api_pb_server.erl\"},
{line,418}]},
{riak_api_pb_server,
 connected,2,
 [{file,
 \"src/riak_api_pb_server.erl\"},
{line,252}]},
{riak_api_pb_server,
 decode_buffer,2,
 [{file,
 \"src/riak_api_pb_server.erl\"},
{line,394}]},
{gen_fsm,
 handle_msg,7,
 [{file,
 \"gen_fsm.erl\"},
{line,505}]},
{proc_lib,
 init_p_do_apply,3,
 [{file,
 \"proc_lib.erl\"},
{line,239}]}]">>}}]},
```

**Comment by macintux** [comment]
Good catch, thanks.

-John

**Comment by macintux** [comment]
Digging into this I realized I could make the parser interface cleaner by using smarter tagged tuples than simply `{ok, Response}`. More commits to come for both repos.

**Comment by macintux** [comment]
Ready for review

**Comment by hazen** [comment]
Unit tests pass.  Trying integration now.

**Comment by hazen** [comment]
Now that it builds, we face our old nemesis, Dialyzer:

```
==> riak_kv (dialyzer)
riak_kv_pb_timeseries.erl:515: The variable SQL can never match since previous clauses completely covered the type {'error',_}
riak_kv_pb_timeseries.erl:525: Function convert_cover_list/2 will never be called
riak_kv_pb_timeseries.erl:545: Function assemble_ts_range/2 will never be called
riak_kv_pb_timeseries.erl:562: Function sql_to_cover/4 will never be called
riak_kv_pb_timeseries.erl:578: Function reverse_sql/1 will never be called
riak_kv_pb_timeseries.erl:588: Function derive_description/3 will never be called
riak_kv_pb_timeseries.erl:596: Function pick_operator/2 will never be called
riak_kv_pb_timeseries.erl:601: Function extract_time_boundaries/2 will never be called
riak_kv_pb_timeseries.erl:613: Function identify_quantum_field/1 will never be called
riak_kv_pb_timeseries.erl:618: Function find_hash_fn/1 will never be called
riak_kv_pb_timeseries.erl:643: The pattern {'ok', Queries} can never match the type {'error','full table scan not implemented' | 'query is already compiled'}
riak_kv_pb_timeseries.erl:658: The call riak_kv_pb_timeseries:make_tsqueryresp(Data::[[any(),...]]) will never return since it differs in the 1st argument from the success typing arguments: ({_,_,[[boolean() | binary() | [any()] | number()]]})
riak_kv_pb_timeseries.erl:810: Function make_tsqueryresp/1 has no local return
riak_kv_pb_timeseries.erl:810: The pattern {_, _, []} can never match the type [[any(),...]]
riak_kv_pb_timeseries.erl:812: The pattern {ColumnNames, ColumnTypes, JustRows} can never match the type [[any(),...]]
riak_kv_qry.erl:102: The pattern {'ok', Queries} can never match the type {'error','full table scan not implemented' | 'query is already compiled'}
riak_kv_qry.erl:110: Function maybe_await_query_results/1 will never be called
make: *** [dialyzer-run] Error 1
```

**Comment by macintux** [comment]
thanks, looking

**Comment by hazen** [comment]
:+1: 213ca77

**Comment by hazen** [comment]
@borshop merge

**Pull request merged**
