### PR TITLE
Do not crash riak node if vnode status file is unreadable

### PR DESCRIPTION
**Pull request by russelldb**
If for any reason the vnode status file is unreadable with
`file:consult/1` the vnode would start, fail to consult, crash until
the restart limit was hit and the node would fail to start/crash.

This change makes that more robust by simply throwing away a status file
that cannot be read, and using a new, empty vnode status. This has the
cost of a new vnodeid+epoch counter for the vnode, but is more robust.

Some vnode files are un-consultable because they were written with
io_lib:format("~p.", [Term]). `io:format' docs say:

```
"Writes the data with standard syntax in the same way as ~w, but breaks
terms whose printed representation is longer than one line into many
lines and indents each line sensibly. It also tries to detect lists of
printable characters and to output these as strings."
```

Which is why this change also use `io_lib:format("~w.", [Term])` to
write vnode status files. This is backwards compatible so these status
files can be read on r16 and previous riaks in the case of downgrade.

----- AH BUT don't conflate erlang 17 handling with corrupt vnode status file!

### CODE REVIEW

**Comment by jonmeredith** [comment]
+1 e973af0f3ecd12c94574d79bb967c557e02f40e5

Created a new issue to request some extra logging #1117 (RIAK-1809) but want to get this merged.

For review:

Confirmed manual recreation of the error -- started fresh node, stopped node, corrupted data/kv_vnode/0, started node, supervisor limit hit then crash.

```
2015-05-15 06:19:51.454 [error] <0.638.0> gen_server <0.638.0> terminated with reason: no match of right hand value {error,{2,erl_parse,["syntax error before: ","'['"]}} in riak_kv_vnode_status_mgr:handle_call/3 line 178
2015-05-15 06:19:51.455 [error] <0.638.0> CRASH REPORT Process <0.638.0> with 0 neighbours exited with reason: no match of right hand value {error,{2,erl_parse,["syntax error before: ","'['"]}} in riak_kv_vnode_status_mgr:handle_call/3 line 178 in gen_server:terminate/6 line 744
2015-05-15 06:19:51.455 [error] <0.616.0> gen_fsm <0.616.0> in state started terminated with reason: no function clause matching riak_kv_vnode:terminate({{{badmatch,{error,{2,erl_parse,["syntax error before: ","'['"]}}},[{riak_kv_vnode_status_mgr,...},...]},...}, undefined) line 1155
2015-05-15 06:19:51.455 [error] <0.616.0> CRASH REPORT Process <0.616.0> with 0 neighbours exited with reason: no function clause matching riak_kv_vnode:terminate({{{badmatch,{error,{2,erl_parse,["syntax error before: ","'['"]}}},[{riak_kv_vnode_status_mgr,...},...]},...}, undefined) line 1155 in gen_fsm:terminate/7 line 600
2015-05-15 06:19:51.455 [error] <0.165.0> Supervisor riak_core_vnode_sup had child undefined started with {riak_core_vnode,start_link,undefined} at <0.616.0> exit with reason no function clause matching riak_kv_vnode:terminate({{{badmatch,{error,{2,erl_parse,["syntax error before: ","'['"]}}},[{riak_kv_vnode_status_mgr,...},...]},...}, undefined) line 1155 in context child_terminated
2015-05-15 06:19:51.456 [error] <0.162.0> Supervisor riak_core_sup had child riak_core_vnode_manager started with riak_core_vnode_manager:start_link() at <0.193.0> exit with reason {{function_clause,[{riak_kv_vnode,terminate,[{{{badmatch,{error,{2,erl_parse,["syntax error before: ","'['"]}}},[{riak_kv_vnode_status_mgr,handle_call,3,[{file,"src/riak_kv_vnode_status_mgr.erl"},{line,178}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]},{gen_server,call,[<0.638.0>,{vnodeid,10000},20000]}},undefined],[{file,"src/riak_kv_vnode.erl"},{line,1155}]},{riak_core_vnode,terminate,3,[{file,"src/riak_..."},...]},...]},...} in context child_terminated
```

and the sad node crash

```
2015-05-15 06:20:31.604 [error] <0.162.0> Supervisor riak_core_sup had child riak_core_vnode_manager started with riak_core_vnode_manager:start_link() at <0.2081.0> exit with reason reached_max_restart_intensity in context shutdown
2015-05-15 06:20:31.622 [info] <0.161.0>@riak_core_app:stop:114 Stopped  application riak_core.
```

Reverted the code fix and ran the test, checked it failed.

Restarted my crashed node with the patch applied and saw the expected error message.

```
2015-05-15 06:39:53.983 [error] <0.648.0>@riak_kv_vnode_status_mgr:read_vnode_status:342 Failed to consult vnode-status file "./data/kv_vnode/0" {error,{2,erl_parse,["syntax error before: ","'['"]}}
```

and confirm vnode status file rewritten

``````
➜  riak git:(2.1) cat data/kv_vnode/0
[{counter,10000},{last_epoch,693593983945},{version,2},{vnodeid,<<35,9,254,249,125,108,75,201>>}].%                                                                                                                              ➜  riak git:(2.1) cat data/kv_vnode/0.before 
ohnoes
[{counter,10000},
 {last_epoch,692292466348},
 {version,2},
 {vnodeid,<<"#\t??/ض?">>}].
➜  riak git:(2.1) cat data/kv_vnode/0       
[{counter,10000},{last_epoch,693593983945},{version,2},{vnodeid,<<35,9,254,249,125,108,75,201>>}].%                                                                                                                              ```
``````

**Comment by jonmeredith** [comment]
+1 e973af0
@bors retry

**Comment by jonmeredith** [comment]
@borshop retry

**Comment by jonmeredith** [comment]
@borshop retry

Looks like unrelated transient failures with riak_kv_pb_object

**Comment by jonmeredith** [comment]
@borshop retry

**Comment by macintux** [comment]
@borshop retry

(because why not?)

**Comment by macintux** [comment]
@borshop: retry

(oops)

**Comment by macintux** [comment]
Original errors caused by the lack of epmd running on the builder. New errors under investigation. Saw same (or at least similar) on other builds, so also expected to be unrelated to this PR.

**Comment by macintux** [comment]
Now have seen two different failures that I haven't been able to reproduce by invoking the test suite individually.

This one in particular seems relevant, and strikes me as a likely cross-test pollution problem:

```
 riak_kv_vnode:blocking_test_/0: Blocking
     Failure/Error: ?assertEqual(0, Cnt)
       expected: 0
            got: 60000
     %% src/riak_kv_vnode.erl:2635:in `riak_kv_vnode:-blocking_test_/0-fun-14-/0`
```

The other is a timeout in `riak_kv_stat:create_or_update_histogram_test/0`.

**Comment by macintux** [comment]
The `riak_kv_vnode:blocking_test` failure can be reproduced by running two modules in order. 

```
2> eunit:test([riak_kv_pb_object,riak_kv_vnode]).
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
riak_kv_vnode: blocking_test_ (Blocking)...*failed*
in function riak_kv_vnode:'-blocking_test_/0-fun-2-'/2 (src/riak_kv_vnode.erl, line 2635
)
in call from riak_kv_vnode:'-blocking_test_/0-fun-14-'/0 (src/riak_kv_vnode.erl, line 26
35)
**error:{assertEqual_failed,[{module,riak_kv_vnode},
                     {line,2635},
                     {expression,"Cnt"},
                     {expected,0},
                     {value,140000}]}
```

**Update**: can reproduce this without `riak_kv_pb_object` involved, haven't come up with another minimal set of modules yet.

**Update 2**: can reproduce with `riak_kv_multi_backend` running before `riak_kv_vnode`.

**Update 3**: all of the above is true on `develop` as well

**Comment by jonmeredith** [comment]
@borshop retry

After John Daily's tireless eunit crushing

**Comment by macintux** [comment]
@jonmeredith we're still missing approval/merge on #1121 for this

**Comment by macintux** [comment]
Once #1133 and #1122 are merged we can try this again. Former is mandatory, latter just to avoid a potential extra retry cycle

**Comment by macintux** [comment]
@borshop merge

**Pull request merged**
