### PR TITLE
spawn writes to folsom, cache reads via riak core stat cache

### PR DESCRIPTION
**Pull request by russelldb**
After testing, reading and writing stats concurrently slowed Riak's general throughput. Short of a process per stat (ideal) or re-introducing the gen_server (possible), spawning for each update seems like a reasonable compromise.

Also, use new stat cache provided by core.

### CODE REVIEW

**Comment by beerriot** [comment]
It looks like some set of tests needs to start `riak_core_stat_cache` now. I'm seeing several of these print during eunit:

```
*** context setup failed ***
::{noproc,{gen_server,call,
                    [riak_core_stat_cache,
                     {register,riak_kv,{riak_kv_stat,produce_stats,[]},5}]}}
```

**Comment by russelldb** [comment]
I just don't see these errors…I tried with master, then a I tried again with the rdb-stat-cache branch.

To be sure I did a clean checkout of riak_kv, ran `rebar get-deps compile` then `./rebar eunit skip-deps=true`. I got some setup failures saying mochiweb was not started.

I checked out `rdb-stat-cache` and ran `./rebar delete-deps get-deps compile` followed by `./rebar eunit skip-deps=true` and the same setup failures. No mention of `riak_core_stat_cache`.

There are some broken windows that need mending. I'm going to try and get _all_ the tests passing in the morning.

**Comment by russelldb** [comment]
Hmm, maybe this commit https://github.com/basho/riak_kv/commit/e069497fbe9a312178790d7233ab38c16487d91e is the reason I don't see these errors.

**Comment by russelldb** [comment]
Further, the tests that are broken still seem to be mapred_test. The problems (I fixed) then saw that they're addressed already by #353 which prompted Sean to add #354.

Please re-run this branch and see if you still get the same failures.

**Comment by beerriot** [comment]
Yep, I must have had a version mismatch somewhere. Re-running as you did on just a KV checkout, and also on a fresh top-level riak checkout, shows no `riak_core_stat_cache` errors. +1 mege

**Comment by russelldb** [comment]
Thanks!

**Pull request closed without merging**
