### PR TITLE
Add sys_monitor_count and sys_port_count to stats.

### PR DESCRIPTION
**Pull request by jonmeredith**
Permits tracking of potentially leakable resources.  Calculating monitors does come at the cost of traversing all processes, but no other way I can see.  Worth a discussion if it's worth it.  The stats are cached so it shouldn't happen too frequently, and only affects one process at a time.

### CODE REVIEW

**Comment by jonmeredith** [comment]
@cmeiklejohn may help with basho/riak_repl#576 et al

**Comment by slfritchie** [comment]
/me Checks thrice for correct ticket number...

+1

**Comment by cmeiklejohn** [comment]
Given this is bors, you gotta :+1: the SHA, so I'll do that for you give you've already :+1:'d the review.

:+1: 1ab3720

**Comment by jonmeredith** [comment]
@borshop merge please

**Comment by Vagabond** [comment]
+1 1ab3720

(the bors commands needs to be on the first line).

**Comment by cmeiklejohn** [comment]
Welp.

**Comment by cmeiklejohn** [comment]
@borshop retry

**Comment by jonmeredith** [comment]
@borshop: retry

**Comment by jonmeredith** [comment]
@borshop: retry

**Comment by reiddraper** [comment]
You need to comment on the commit itself to get borshop to retry. KV is also failing now that EQC was turned on. @vinoski and I have been looking into it today.

**Comment by jonmeredith** [comment]
@borshop: retry

**Comment by reiddraper** [comment]
@jonmeredith @borshop is picky now, and you must comment on the commit itself. I've kicked off another build already, but the KV queue is rather long at the moment. Should hear back in under two hours I hope.

**Comment by jonmeredith** [comment]
@reiddraper dialyzer failed again :(

```
riak_kv_mrc_map.erl:76: The return type {'error',_} in the specification of init/2 is not a subtype of {'ok',_}, which is the expected return type for the callback of riak_pipe_vnode_worker behaviour
make: *** [dialyzer] Error 1
```

Is this resolved in any of your fixings?

**Comment by reiddraper** [comment]
@jonmeredith I've not seen that, but I've got free cycles today to look into it. Building that branch locally now.

**Comment by reiddraper** [comment]
#941 should fix that dialyzer error. Once it's merged in, we'll retry this build.

**Comment by reiddraper** [comment]
@borshop merge!

**Pull request merged**
