### PR TITLE
forward port membackend fixes

### PR DESCRIPTION
**Pull request by evanmcc**
port of #940, #957, & #717 to develop.

cc @reiddraper @kellymclaughlin

### CODE REVIEW

**Comment by evanmcc** [comment]
bah, look have broken some eunit and dialyzer stuff, fixed to come on monday morning.

**Comment by evanmcc** [comment]
apparently the ignore stuff is line-specific.  not sure what to ignore and what to leave in.  will consult with the gurus tomorrow morning.

**Comment by reiddraper** [comment]
@evanmcc ping me today if you like re: dialyzer stuffs

**Comment by evanmcc** [comment]
OK, this is updated and looks ready to review.  Have also pushed a new version of the riak_test.

**Comment by reiddraper** [comment]
Ok reviewing again

**Comment by reiddraper** [comment]
+1, works for me now, thanks

**Comment by cmeiklejohn** [comment]
:+1: 6cd0376

**Comment by evanmcc** [comment]
@borshop: merge

**Pull request merged**
