### PR TITLE
add riak_pb to apps in src/riak_kv.app.src

### PR DESCRIPTION
**Pull request by vinoski**
The riak_pb app is used in riak_kv but was not listed as an application
dependency in the src/riak_kv.app.src file.

Also add missing apps to riak_kv_test_util code that manages
starting/stopping application dependencies for testing.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
`eunit` stalls on me, but otherwise it looks good and builds.

```
module 'riak_kv_pb_object'

=INFO REPORT==== 18-Nov-2013::19:05:06 ===
    application: bitcask
    exited: stopped
    type: temporary
```

**Comment by vinoski** [comment]
Commit amended, should be OK now.

**Comment by cmeiklejohn** [comment]
Confirmed the amended commit resolves the hangs in the test suite.  

```
  All 286 tests passed.
```

**Comment by cmeiklejohn** [comment]
:+1:

**Comment by seancribbs** [comment]
Note `riak_pb` is a dependency of `riak_api`, should it need to be listed in the dependent apps?

**Comment by vinoski** [comment]
`riak_kv` code uses `riak_pb` code directly, so I'd say yes. Seems wrong to count on picking up direct dependencies via other dependencies.

**Comment by cmeiklejohn** [comment]
I agree with @vinoski, but I'm up for the discussion.

**Comment by vinoski** [comment]
In fact, perhaps the `rebar.config` for `riak_kv` should explicitly list `riak_pb` as a dep as well, for the same reason.

**Comment by seancribbs** [comment]
@vinoski Disagree with rebar.config change, that just makes it harder to roll versions.

**Comment by vinoski** [comment]
@seancribbs Understood, and that's definitely the practical conclusion, but I think one could argue that problem is really a rebar issue...

**Comment by seancribbs** [comment]
@vinoski Agree, but the day that rebar works that way is not today. :smile_cat:

**Pull request merged**
