### PR TITLE
Addresses test failures when epmd is not running

### PR DESCRIPTION
**Pull request by macintux**
Addresses #1112

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Are you getting a clean run with this, or is it just removing a subset of the errors?

**Comment by macintux** [comment]
Double checking. I know the test in question passes with `epmd` running, and doesn't pass with it not running, and I know `make test` seems to work with this change, but I haven't compared the # of tests run with and without.

**Comment by macintux** [comment]
Yep, something's off. 296 successes either way, 4 failures on develop. Thanks for pointing this out; do you know what's going on?

**Comment by macintux** [comment]
Scratch that: I was misreading eunit's output. Derp. 296 _tests_, not 296 successes. Is there something you specifically were concerned about, @cmeiklejohn?

**Comment by cmeiklejohn** [comment]
:+1: 8eb9c1a

**Comment by macintux** [comment]
@borshop merge

**Pull request merged**
