### PR TITLE
move ddl validation to riak_ql_parser, add more DDL validation checks

### PR DESCRIPTION
**Pull request by hmmr**
RTS-616, RTS-620, RTS-623 (items D, H, J in RTS-610).

Depends on https://github.com/basho/riak_ql/pull/50, where checks are now being done.

Corresponding r_t modules are added in https://github.com/basho/riak_test/pull/943.

### CODE REVIEW

**Comment by hazen** [comment]
@hmmr SOOO happy to get this out of WebMachine code!

**Comment by hazen** [comment]
Failing unit tests

```
  riak_kv_console: bucket_type_create_with_timeseries_table_error_with_short_primary_key_test...*failed*
in function riak_kv_console:'-bucket_type_create_with_timeseries_table_error_with_short_primary_key_test/0-fun-1-'/3 (src/riak_kv_console.erl, line 994)
**error:{assertEqual_failed,[{module,riak_kv_console},
                     {line,994},
                     {expression,"bucket_type_create ( fun ( Props ) -> put ( Ref , Props ) end , << \"my_type\" >> , mochijson2 : decode ( JSON ) )"},
                     {expected,error},
                     {value,undefined}]}


  riak_kv_console: bucket_type_create_with_timeseries_table_error_with_misplaced_quantum_test...ok
  riak_kv_console: bucket_type_and_table_error_local_key_test...*failed*
in function riak_kv_console:'-bucket_type_and_table_error_local_key_test/0-fun-1-'/3 (src/riak_kv_console.erl, line 1035)
**error:{assertEqual_failed,[{module,riak_kv_console},
                     {line,1035},
                     {expression,"bucket_type_create ( fun ( Props ) -> put ( Ref , Props ) end , << \"my_type\" >> , mochijson2 : decode ( JSON ) )"},
                     {expected,error},
                     {value,undefined}]}
```

**Comment by hazen** [comment]
:+1: 22a0358

**Comment by hmmr** [comment]
@borshop merge

**Pull request merged**
