### PR TITLE
Remove full object as context code and use DT's built in contexts

### PR DESCRIPTION
**Pull request by russelldb**
Depends on https://github.com/basho/riak_dt/pull/83. See also riak_test PR at https://github.com/basho/riak_test/pull/552

### CODE REVIEW

**Comment by seancribbs** [comment]
If you're removing the EQC prop in `riak_kv_crdt`, can you also remove the `Makefile` hack (the `test-compile` target)? Other than that, :+1: much simpler code

**Comment by russelldb** [comment]
Push `Makefile` change. Waiting on DT thumbs up before merging.

**Comment by seancribbs** [comment]
:+1: 6dab13e

**Comment by seancribbs** [comment]
:+1: to merge

**Pull request merged**
