### PR TITLE
"stream" is an optional boolean

### PR DESCRIPTION
**Pull request by lukebakken**
Fix error introduced in ccb019fd

Please see [this comment](https://github.com/basho/riak_kv/commit/ccb019fdc02ad545a9914adc391c56d423550630#commitcomment-19105226)

### CODE REVIEW

**Comment by JeetKunDoug** [comment]
@fadushin we need to get this included in the next RC, as our protobuf library seems to not be quite "compliant" when it comes to booleans and default values, which @lehoff and I missed when we made this change.

**Comment by lukebakken** [comment]
Yes, the library does not follow the spec, and does not use the type-specific default when no value is present to be decoded in an `optional` field. Instead, you get `undefined`, presumably so the decoding side can "know" if a value was present or not. I am sure we depend on this behavior throughout Riak.

However, just so you know, if an `optional` field uses the `default` option to set a default value, that value _will_ be used during decoding if no data is present for that field.

**Comment by JeetKunDoug** [comment]
FYI - rebased this on top of develop-2.2 so tests should pass.

**Comment by JeetKunDoug** [comment]
Rerunning tests now that Lager fixes are in place in upstream (downstream?) dependencies. Should build/test clean now.

**Comment by ian-mi** [comment]
+1

**Comment by JeetKunDoug** [comment]
+1 99c92ed

**Comment by JeetKunDoug** [comment]
@borshop merge

**Pull request merged**
