### PR TITLE
Expose logs about AAE tree status.

### PR DESCRIPTION
**Pull request by ksauzz**
I hope these logs would be exposed to riak operators in info level. These logs help them understand how much time AAE take to have built a tree, and also how AAE works. 

I'd like to backport this to version 1.4.x if this is acceptable.

### CODE REVIEW

**Comment by slfritchie** [comment]
US Basho folk -- it'd be lovely to see rough consensus in favor of this PR.

**Comment by seancribbs** [comment]
Could this be solved with lager:trace_file/2,3,4 instead of raising the level?

Alternately, could the messages be improved so it's clearer that these are from AAE?

**Comment by slfritchie** [comment]
@seancribbs I can't answer that as well as Kaz, so I'll let him choose.  AFAIK, those status messages aren't intended for occasional inspection but for watching/monitoring forever.

**Comment by ksauzz** [comment]
> Could this be solved with lager:trace_file/2,3,4 instead of raising the level?

No, it couldn't. To help operators expect the elapsed time by next tree build, we should provide permanent logging of AAE tree build. lager:trace_file/2,3,4 can't be enabled permanently. So It looks a temporary workaround for me.

> Alternately, could the messages be improved so it's clearer that these are from AAE?

My proposal is the following:

``` diff
--- a/src/riak_kv_index_hashtree.erl
+++ b/src/riak_kv_index_hashtree.erl
@@ -802,7 +802,7 @@ maybe_expire(State) ->

 -spec clear_tree(state()) -> state().
 clear_tree(State=#state{index=Index}) ->
-    lager:info("Clearing tree ~p", [Index]),
+    lager:info("Clearing AAE tree: ~p", [Index]),
     IndexNs = responsible_preflists(State),
     State2 = destroy_trees(State),
     State3 = init_trees(IndexNs, State2#state{trees=orddict:new()}),
@@ -840,14 +840,14 @@ build_or_rehash(Self, State=#state{index=Index}) ->
 build_or_rehash(Self, Locked, Type, #state{index=Index, trees=Trees}) ->
     case {Locked, Type} of
         {true, build} ->
-            lager:info("Starting build: ~p", [Index]),
+            lager:info("Starting AAE tree build: ~p", [Index]),
             fold_keys(Index, Self, has_index_tree(Trees)),
-            lager:info("Finished build (a): ~p", [Index]),
+            lager:info("Finished AAE tree build (a): ~p", [Index]),
             gen_server:cast(Self, build_finished);
         {true, rehash} ->
-            lager:info("Starting rehash: ~p", [Index]),
+            lager:info("Starting AAE tree rehash: ~p", [Index]),
             _ = [hashtree:rehash_tree(T) || {_,T} <- Trees],
-            lager:info("Finished rehash (a): ~p", [Index]),
+            lager:info("Finished AAE tree rehash (a): ~p", [Index]),
```

**Comment by ksauzz** [comment]
It was not necessary to change log level of 'rehash'. I'll change them back to debug level.

**Comment by seancribbs** [comment]
@ksauzz I like those messages better, thanks. Go ahead and make the change, either @slfritchie or I can give the :+1:

**Comment by seancribbs** [comment]
:+1: 06efea6

**Comment by ksauzz** [comment]
Thanks! I made the changes, and pushed them. But buildbot looks failed... :(

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
