### PR TITLE
Return empty tsgetresp message back if row was not found

### PR DESCRIPTION
**Pull request by alexmoore**

### CODE REVIEW

**Comment by lukebakken** [comment]
Looks good to me. Is there a way to add a test for this?

**Comment by lukebakken** [comment]
@hmmr @bkerley and I think that this should continue to return `notfound` like KV does.

**Comment by hmmr** [comment]
I'd rather agree with gentlemen, but it's not a particularly strong opinion that I have.

Note that in the Erlang client, currently the notfound case is effectively re-translated into an empty-list form: https://github.com/basho/riak-erlang-client/blob/end-to-end/timeseries/src/riakc_ts.erl#L128.

**Comment by hazen** [comment]
I'll test it by seeing if I can add a test :wink:

**Comment by hmmr** [comment]
I propose to escalate this issue and seek an administrative ruling. It pretty much is of the same rank as the type renaming revolution we have been through days ago.

**Comment by hazen** [comment]
@hmmr Just grabbed Heather in the hallway and she seemed pretty happy with @alexmoore's proposed fix.

**Comment by hazen** [comment]
@borshop merge

**Pull request merged**
