### PR TITLE
prevent secondary systems (e.g. yz) from blocking vnode handoff forever

### PR DESCRIPTION
**Pull request by jrwest**
- add a recejection count and maximum number of rejections (configurable)
- includes changes to riak_kv.schema

addresses: https://github.com/basho/yokozuna/issues/417
test: https://github.com/basho/yokozuna/pull/418
test depends on: https://github.com/basho/riak_test/pull/671
riak_kv.schema doc changes depend on: https://github.com/basho/riak_core/pull/621

### CODE REVIEW

**Comment by jrwest** [comment]
cc/ @seancribbs for the `riak_kv.schema` changes

**Comment by seancribbs** [comment]
Schema test for changes to riak_kv.schema?

**Comment by jrwest** [comment]
schema test pushed

**Comment by coderoshi** [comment]
- [x] code review 
- [x] unit tests
- [x] riak test

**Comment by coderoshi** [comment]
+1 af22b38

**Comment by jrwest** [comment]
@borshop merge

**Comment by jrwest** [comment]
@borshop merge

**Comment by jrwest** [comment]
@borshop merge

**Comment by jrwest** [comment]
ah I think this isn't merging because @borshop needs the +1 on https://github.com/basho/riak_kv/commit/6af8b594559f4af7e02a610131449328b56f952e#diff-d41d8cd98f00b204e9800998ecf8427e instead of af22b38

**Comment by coderoshi** [comment]
+1 6af8b59

oi

**Comment by jrwest** [comment]
@borshop merge

**Pull request merged**
