### PR TITLE
Add config entry for riak_dt.binary_compression.

### PR DESCRIPTION
**Pull request by seancribbs**
See basho/riak_dt#77 for setting details.
- [x] Eng +1
- [x] PM +1
- [x] CSE +1

### CODE REVIEW

**Comment by jmshoffs0812** [comment]
CSE +1

**Comment by seancribbs** [comment]
NB: this is in riak_kv so as not to incur the cuttlefish dependency on riak_dt.

**Comment by gburd** [comment]
PM +1

**Comment by joedevivo** [comment]
code looks good. tests pass. oneplus.

**Pull request merged**
