### PR TITLE
Cleaner output for bucket type creation errors

### PR DESCRIPTION
**Pull request by macintux**
Could probably be further enhanced, but handles the problem reported by @jrwest in #893 much more gracefully.

```
$ ./riak-admin bucket-type create foo '{"props": {"r": "fred", "n_val": "abc", "consistent": "abc", "allow_mult": "x"}}'
Error creating bucket type foo:
r must be an integer or (one|quorum|all)
n_val must be an integer
allow_mult should be true or false
<<"abc">> is not a valid value for consistent. Use "true" or "false"
```

### CODE REVIEW

**Comment by jrwest** [comment]
`bucket-type update` has the same issue:

```
$ dev/dev1/bin/riak-admin bucket-type update abc '{"props": {"n_val": "def", "allow_mult": "yaya"}}' 
Error updating bucket type abc: [{allow_mult,not_boolean},{n_val,not_integer}]
```

**Comment by macintux** [comment]
Noted, will revise and extend.

**Comment by macintux** [comment]
I'd made a mental note to update this function too, sigh. Anyway, updated, ran more tests, looked for any other functions that might need this.

**Comment by jrwest** [comment]
+1 ed9a17a

**Comment by macintux** [comment]
@borshop merge

**Pull request merged**
